wireapp/core-crypto

- crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
- crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
- crypto-ffi/bindings/swift/Tests/CoreCryptoTests/CoreCryptoTests.swift
- crypto-ffi/bindings/swift/include/core_cryptoFFI.h
- crypto-ffi/src/CoreCrypto.udl
- crypto-ffi/src/lib.rs
- crypto-ffi/tests/bindings_tests.rs
- crypto/src/client.rs
- crypto/src/conversation.rs
- crypto/src/lib.rs
- keystore/Cargo.toml
- keystore/src/mls.rs
Closes #12 
----
----
Cf #12 
Make sure we return the correct number of KPBs
----
----
----
> fix: Incorrect number of keypackages returned [CL-11]

- .github/workflows/rust.yml
- Cargo.toml
- crypto-ffi/Cargo.toml
- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto-ffi/bindings/js/test/CoreCrypto.test.js
- crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
- crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
- crypto-ffi/bindings/swift/include/core_cryptoFFI.h
- crypto-ffi/src/CoreCrypto.udl
- crypto-ffi/src/generic.rs
- crypto-ffi/src/generic/c_api/c_api_tests.rs
- crypto-ffi/src/generic/c_api/mod.rs
- crypto-ffi/src/generic/uniffi_support.rs
- crypto-ffi/src/wasm.rs
- crypto/src/error.rs
- crypto/src/lib.rs
- keystore/Cargo.toml
- keystore/tests/common.rs
- keystore/tests/mls.rs
- mls-provider/Cargo.toml
- mls-provider/src/crypto_provider.rs
- mls-provider/src/error.rs
- mls-provider/src/lib.rs
- mls-provider/tests/crypto.rs
- mls-provider/tests/fixtures.rs
- mls-provider/tests/randomness.rs
- package.json
----
----
Ability to insert external entropy from outside of `getrandom`
* Added an ability to insert external entropy from outside of `getrandom`
* Added support for P384 ciphersuites
* Note: P521 code is ready but the Rust `p521` crate is not ready yet
* Note: Ed448 support is an unknown. There's no official RustCrypto crate for it and the others are very much manual things and getting your hands dirty
```
cd mls-provider
cargo test
```
A lot of parametric tests have been added to the MLS provider, to test using all the scenarios: storage backends, ciphersuites, etc
----
----
----
1. E.g. `feat(conversation-list): Sort conversations by most …
> feat: Add ability to manually seed the PRNG entropy pool [CL-38]

- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
- crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
- crypto-ffi/bindings/swift/include/core_cryptoFFI.h
- crypto-ffi/src/CoreCrypto.udl
- crypto-ffi/src/generic.rs
- crypto-ffi/src/wasm.rs
- crypto/src/client.rs
- crypto/src/conversation.rs
- crypto/src/error.rs
- crypto/src/lib.rs
- keystore/Cargo.toml
- keystore/src/connection/mod.rs
- keystore/src/connection/platform/wasm/mod.rs
- keystore/src/connection/platform/wasm/storage.rs
- keystore/src/entities/mod.rs
- keystore/src/entities/platform/generic/mls/group.rs
- keystore/src/entities/platform/generic/mls/identity.rs
- keystore/src/entities/platform/generic/mls/keypackage.rs
- keystore/src/entities/platform/generic/proteus/mod.rs
- keystore/src/entities/platform/wasm/mls/group.rs
- keystore/src/entities/platform/wasm/mls/identity.rs
- keystore/src/entities/platform/wasm/mls/keypackage.rs
- keystore/src/entities/platform/wasm/proteus/mod.rs
- keystore/src/error.rs
- keystore/src/mls.rs
- keystore/tests/common.rs
- keystore/tests/z_entities.rs
- mls-provider/tests/fixtures.rs
- mls-provider/tests/randomness.rs
* Previous PR here: #32
----
----
Keypackages that were past their configured lifetime would stay in the keystore, leading to duplication and maybe multi-use of Keypackages
* Added an API to allow consumers to manually prune uploaded Keypackages from the Keystore
* Added warnings that this can be misused and direct calls to the method implies that the consumer knows what they're doing
* Add an API to get the count of valid KeyPackages.
* Added automatic calls to the keypackage pruning method to ensure lifetime-expired keypackages are removed from the store
* ~~Added automatic keypackage pruning of keypackage refs covered by a Welcome message~~
* Edit: This has been discarded as OpenMLS does it internally already
* WASM API fixes + Added rustdoc …
> feat: Implement KeyPackage pruning [CL-16] Redux

- crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
- crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
- crypto-ffi/bindings/swift/include/core_cryptoFFI.h
- crypto-ffi/src/CoreCrypto.udl
- crypto-ffi/src/generic.rs
- crypto-ffi/src/wasm.rs
- crypto/src/commit_delay.rs
- crypto/src/conversation.rs
- crypto/src/credential.rs
- crypto/src/error.rs
- crypto/src/external_commit.rs
- crypto/src/lib.rs
- crypto/src/member.rs
- crypto/src/test_fixture_utils.rs
----
----
Adds a commit delay value for clients to not possibly DDOS the backend with all of the sending commits at the same time.
----
----
> feat!: add commit delay when a message with prending proposals is processed [CL-52]

- crypto/src/conversation/commit_delay.rs
- crypto/src/conversation/decrypt.rs
----
----
* refactor `commit_delay` mod
* return a delay when decrypting a commit and there are pending proposals
----
> return commit delay when decrypting commit [CL-52]

- crypto/src/client.rs
- crypto/src/conversation/decrypt.rs
- crypto/src/conversation/handshake.rs
- crypto/src/conversation/merge.rs
- crypto/src/conversation/mod.rs
- crypto/src/conversation/renew.rs
- crypto/src/credential.rs
- crypto/src/external_commit.rs
- crypto/src/external_proposal.rs
- crypto/src/lib.rs
- crypto/src/member.rs
- crypto/src/proposal.rs
- crypto/src/test_utils.rs
----
----
So far testing was a bit cumbersome. We were using both `MlsConversation` and `MlsCentral` in our tests. There was test helpers in all sorts of places etc.. What this PR will bring
* all tests (whenever possible) will use `MlsCentral` to perform operations. Using `MlsConversation` should be abandonned. This brings better coverage and will help in case the method in central is not a pass through
* All test helpers should be in `test_utils` mod
* Added `MlsCentral::can_talk_to(&mut self, id: &ConversationId, other: &mut MlsCentral)` to streamline the process of verifying if 2 central can exchange messages
* Added `MlsCentral::invite(&mut self, id: &ConversationId, mut other: &mut MlsCentral)` to cut all the boilerplate of adding a user …
> Cleaner and less verbose tests

- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
- crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
- crypto-ffi/bindings/swift/include/core_cryptoFFI.h
- crypto-ffi/src/CoreCrypto.udl
- crypto-ffi/src/generic.rs
- crypto-ffi/src/wasm.rs
- crypto/src/conversation/decrypt.rs
- crypto/src/conversation/handshake.rs
- crypto/src/conversation/mod.rs
- crypto/src/external_proposal.rs
- crypto/src/proposal.rs
- crypto/src/test_utils.rs
----
----
* all commit methods return a 'CommitBundle' struct holding an optional Welcome message in case pending Add proposals were present
* 'add_members_to_conversation' & 'remove_members_from_conversation' no longer return an optional commit
----
> commits return optional welcome [CL-57]

- crypto/src/conversation/mod.rs
- crypto/src/test_utils.rs
----
----
Reduce the sample size for debug configurations so that the tests don't fail locally because of timeouts.
----
> test: Reducing the sample size for debug configurations so that we avoid timeouts

- crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
- crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
- crypto-ffi/bindings/swift/include/core_cryptoFFI.h
- crypto-ffi/src/CoreCrypto.udl
- crypto-ffi/src/generic.rs
- crypto-ffi/src/wasm.rs
- crypto/src/conversation/mod.rs
- crypto/src/lib.rs
- keystore/src/mls.rs
----
----
Adds an API for the consumer to wipe a specific group from core-crypto.
----
> feat: Add API to wipe specific group from core crypto [CL-55]

- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto-ffi/src/generic.rs
- crypto-ffi/src/wasm.rs
- crypto/src/conversation/decrypt.rs
- crypto/src/conversation/mod.rs
- crypto/src/conversation/renew.rs
- crypto/src/error.rs
- crypto/src/external_commit.rs
- crypto/src/external_proposal.rs
- crypto/src/test_utils.rs
----
----
Consumers can now pass an Ed25519 public key when creating a conversation. This "remove key" is the backend's key which will be used to validate external remove proposals
----
> expose external senders at conversation creation for external remove proposal support [CL-53]

- .github/workflows/rust.yml
- README.md
- crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
- crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
- crypto-ffi/bindings/swift/include/core_cryptoFFI.h
- crypto-ffi/src/CoreCrypto.udl
- crypto-ffi/src/generic.rs
- crypto-ffi/src/wasm.rs
- crypto/src/conversation/decrypt.rs
- crypto/src/error.rs
- crypto/src/external_proposal.rs
----
----
Generate a fresh KeyPackage for external Add proposal instead of requiring one.
Also unrelated but in same PR:
* fix doctests because bash snippets could not compile in Rust
* Add CI step to execute doctests
* Removed unused `SelfKeypackageNotFound` error
* Removed `InvalidProposalType` error by using pattern matching
----
> feat: remove required KeyPackage when creating an external add proposal

- .github/workflows/rust.yml
- CHANGELOG.md
- CHANGELOG.tpl
- xtask/Cargo.lock
- xtask/Cargo.toml
- xtask/src/documentation/changelog.rs
- xtask/src/documentation/mod.rs
- xtask/src/main.rs
- xtask/src/release/bump.rs
- xtask/src/release/mod.rs
Added a new `xtask` to sync bumping up crates versions. Will be useful later on.
> build(tooling): Added semver version bumper

- Cargo.toml
- crypto-attributes/Cargo.toml
- crypto-attributes/src/lib.rs
- crypto/Cargo.toml
- crypto/src/conversation/decrypt.rs
- crypto/src/conversation/durability.rs
- crypto/src/conversation/encrypt.rs
- crypto/src/conversation/handshake.rs
- crypto/src/conversation/merge.rs
- crypto/src/conversation/mod.rs
- crypto/src/conversation/renew.rs
- crypto/src/error.rs
- crypto/src/external_proposal.rs
- crypto/src/lib.rs
----
----
Sometimes, we might forget to persist a MLS group after an operation. This macro will erase the current in memory group and restore it from keystore. If the methods is tested enough and forgets to persist the group (while it should) then the unit tests will catch that
----
> Verify our operations are durable [CL-63]

- crypto/src/conversation/mod.rs
----
----
Use 128 bits of padding by default instead of 16 previously
----
> feat: use 128 bytes of padding when encrypting messages instead of 16

- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
- crypto-ffi/src/CoreCrypto.udl
- crypto-ffi/src/generic.rs
- crypto-ffi/src/wasm.rs
- crypto/src/client.rs
- crypto/src/conversation/decrypt.rs
----
----
Return sender client id when decrypting a message to help AVS
----
> feat!: 'decrypt_message' returns the sender client id [CL-81]

- Cargo.toml
- crypto-attributes/Cargo.toml
----
----
Running core-crypto on Android fails because of a null pointer error in the [sha2](https://github.com/RustCrypto/hashes/tree/master/sha2) crate. The regression was introduced by [this PR](https://github.com/RustCrypto/hashes/pull/388) which narrows down the supported architectures, excluding Android ones. It is likely the [sha2-asm](https://github.com/RustCrypto/asm-hashes) is supported on more targets than it claims.
----
> Fix android null pointer

- Cargo.toml
- crypto-ffi/Cargo.toml
…ot supporting hardware implementation (i686 & armv7 in our case)
----
----
Force software implementation for sha2 on target architectures not supporting hardware implementation (i686 & armv7 in our case).
----
> fix: sha2 on 32 bit Android [CL-83]

- keystore/Cargo.toml
- keystore/src/connection/platform/generic/mod.rs
- keystore/tests/general.rs
Closes #95 
Basically it wasnt working at all anyway because of a syntax error. I have no idea how we could compile for ios before?
> fix: Fixed iOS SQLCipher salt handling within keychain [CL-84]

- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
- crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
- crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
- crypto-ffi/bindings/swift/lib/core_cryptoFFI.h
- crypto-ffi/src/CoreCrypto.udl
- crypto-ffi/src/generic.rs
- crypto-ffi/src/wasm.rs
- crypto/src/conversation/decrypt.rs
- crypto/src/conversation/handshake.rs
- crypto/src/external_proposal.rs
- crypto/src/proposal.rs
----
----
In order to tell the consumer if `commit_pending_proposals` has pending proposals or not we return an optional now instead of an error (more convenient). This also changes the behavior of the method which was an alias for `update_keying_material`
----
> feat!: 'commit_pending_proposals' now returns an optional CommitBundle

- crypto/src/conversation/mod.rs
- crypto/src/external_proposal.rs
----
----
external_senders public key was not TLS deserialized causing rejection of external remove proposals
The backend's key was not TLS deserialized
TLS deserialize the backend's key
----
> fix: external_senders public key was not TLS deserialized

- crypto/src/conversation/mod.rs
- crypto/src/external_proposal.rs
----
----
wire-server sends a base64 encoded ed25519 key afterall. Consumers are in charge of base64 decoding it and pass it to core-crypto
----
> fix: wire-server removal key

- crypto-ffi/src/generic.rs
- crypto-ffi/src/wasm.rs
- crypto/src/client.rs
- crypto/src/conversation/encrypt.rs
- crypto/src/conversation/handshake.rs
- crypto/src/external_commit.rs
----
----
remove unneeded `map_err(CryptoError::from)`
----
> chore: remove unneeded `map_err(CryptoError::from)`

- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
- crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
- crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
- crypto-ffi/bindings/swift/lib/core_cryptoFFI.h
- crypto-ffi/src/CoreCrypto.udl
- crypto-ffi/src/generic.rs
- crypto-ffi/src/wasm.rs
- crypto/src/error.rs
- crypto/src/mls/conversation/export.rs
- crypto/src/mls/conversation/mod.rs
…embers
----
----
Will introduce the possibility to derive a new key from a group and export its client ids.
----
> feat: Exporting secret key derived from the group and client ids from the members - CL-97 - CL-98

- crypto/src/mls/external_commit.rs
- crypto/src/test_utils/fixtures.rs
----
----
Fix the wrong assumption that a member could not rejoin a group by external commit
----
> test: member can rejoin group by external commit [CL-100]

- .github/workflows/publish-swift.yml
- crypto-ffi/bindings/swift/Package.swift
----
----
SPM versions must follow semantic versioning, meaning the tags in the package must be correctly named. iOS team is still on swift 5.5, so downgrading the package to the correct version
----
> fix: Make tags have semantic versioning names and downgrading to swift 5.5 - CL-49

- crypto/src/mls/conversation/handshake.rs
----
----
Commits could lead to inconsistent state in keystore in case PGS serialization fails
----
> fix: consistent commits

- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
- crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
- crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
- crypto-ffi/bindings/swift/lib/core_cryptoFFI.h
- crypto-ffi/src/CoreCrypto.udl
- crypto-ffi/src/generic.rs
- crypto-ffi/src/wasm.rs
- crypto/benches/create_group.rs
- crypto/benches/utils.rs
- crypto/src/error.rs
- crypto/src/lib.rs
- crypto/src/mls/conversation/handshake.rs
- crypto/src/mls/conversation/mod.rs
- crypto/src/mls/credential.rs
- crypto/src/mls/external_commit.rs
- crypto/src/mls/external_proposal.rs
- crypto/src/mls/mod.rs
- crypto/src/proteus.rs
- crypto/src/test_utils/central.rs
- crypto/src/test_utils/fixtures.rs
- crypto/src/test_utils/mod.rs
- interop/src/clients/corecrypto/native.rs
- interop/src/main.rs
----
----
Add:
* `deferred_init` to init `CoreCrypto` keystore without initializing `mls_client`
* `mls_init` to init `mls_client`
----
> feat: support deferred MLS initialization for proteus purposes [CL-106]

- crypto-ffi/README.md
- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
- crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
- crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
- crypto-ffi/bindings/swift/lib/core_cryptoFFI.h
- crypto-ffi/src/CoreCrypto.udl
- crypto-ffi/src/generic.rs
- crypto-ffi/src/wasm.rs
- crypto/src/proteus.rs
----
----
Exposes functions to extract local and remote proteus session fingerprints and adds bindings for missing methods in swift bindings.
----
> feat: Expose proteus session fingerprints (local and remote) - CL-108

- .github/workflows/publish-android.yml
----
----
Github uses NDK 25. We want to use 21 for our android builds.
----
> chore: Use NDK 21 for android artifacts - CL-111

- crypto-ffi/src/CoreCrypto.udl
- crypto-ffi/src/generic.rs
- crypto-ffi/src/wasm.rs
- crypto/src/error.rs
- crypto/src/mls/conversation/config.rs
- crypto/src/mls/conversation/decrypt.rs
- crypto/src/mls/mod.rs
----
----
* Have a specialized error when trying to decrypt from wrong epoch hence trying to violate forward secrecy
* Bring back `out_of_order_tolerance` and `maximum_forward_distance` in our custom configuration, just for testing purposes now
----
> feat: specialized decryption error

- crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
- crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
- crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
- crypto-ffi/bindings/swift/lib/core_cryptoFFI.h
- crypto-ffi/src/CoreCrypto.udl
- crypto-ffi/src/generic.rs
- crypto/src/mls/conversation/mod.rs
- crypto/src/mls/mod.rs
----
----
feat: add 'restore_from_disk' to enable using multiple MlsCentral instances in iOS extensions
----
> feat: add 'restore_from_disk'  [CL-116]

- crypto-ffi/src/CoreCrypto.udl
- crypto/src/error.rs
- crypto/src/mls/conversation/decrypt.rs
- crypto/src/mls/conversation/handshake.rs
- crypto/src/mls/external_commit.rs
----
----
expose a 'WrongEpoch' error whenever one attempts to decrypt a message in the wrong epoch.
----
> feat: expose a 'WrongEpoch' error

- crypto-ffi/src/CoreCrypto.udl
- crypto/src/error.rs
- crypto/src/mls/conversation/decrypt.rs
----
----
while adding more tests to demonstrate some MLS properties, I found out that application messages signed by expired KeyPackages passed verification
----
> feat: verify messages signed by expired KeyPackages

- Cargo.toml
- crypto-ffi/Makefile.toml
----
----
The `aarch64-apple-ios-sim` target is currently disabled since it fails to compile.
OpenSSL and Ring fails to compile.
OpenSSL has has fix but it's not released yet https://github.com/alexcrichton/openssl-src-rs/pull/175
Ring fails due to a bad argument to the compiler:
```
running "clang" "-Os" "-fPIC" "--target=arm64-apple-ios7.0-simulator" "-arch arm64" "-mios-simulator-version-min=7.0" "-isysroot" "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.2.sdk" "-fembed-bitcode" "-Wno-error=inline" "-I" "include" "-I" "/Users/jacob/Development/wire/core-crypto/target/aarch64-apple-ios-sim/release/build/ring-c1f698412350209d/out" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" …
```
> fix: aarch64-apple-ios-sim target not compiling 

- Cargo.toml
- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
- crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
- crypto-ffi/bindings/swift/lib/core_cryptoFFI.h
- crypto-ffi/src/CoreCrypto.udl
- crypto-ffi/src/generic.rs
- crypto-ffi/src/wasm.rs
- crypto/Cargo.toml
- crypto/src/e2e_identity/crypto.rs
- crypto/src/e2e_identity/error.rs
- crypto/src/e2e_identity/mod.rs
- crypto/src/e2e_identity/types.rs
- crypto/src/lib.rs
- crypto/src/test_utils/fixtures.rs
- interop/src/clients/corecrypto/native.rs
- interop/src/clients/corecrypto/web.rs
- interop/src/clients/mod.rs
- interop/src/main.rs
----
----
Add end to end identity bindings for Android. WASM support is partial and to be continued. Swift bindings are not done.
----
> feat: add end to end identity bindings [CL-21]

- keystore/Cargo.toml
- keystore/src/connection/mod.rs
- keystore/src/connection/platform/wasm/mod.rs
- keystore/tests/common.rs
- keystore/tests/general.rs
The IndexedDB store didn't get its upgrade handler triggered, leading to new stores not being created. I made it so that the store version follows a simplified scheme depending on the crate version
> fix: Increment IndexedDB store version when crate version changes [CL-127]

- .github/workflows/publish-jvm.yml
- kotlin/jvm/build.gradle.kts
----
----
Publishing CoreCrypto for the JVM no longer supports linux targets
Building for linux now only possible on a linux host and the CI job for publishing the JVM package runs on a mac host.
Split up up the JVM publish workflow into three jobs which build the library on each native platform and upload the result as a GitHub Artifacts. The final job download the artifacts and creates and publishes the JVM package.
- The `copy-jvm-resources` task is obsolete now since it's now performed by the JVM Gradle file.
----
----
----
> chore: update JVM publish workflow to build on native platforms

- .github/workflows/audit.yml
- .github/workflows/bindings.yml
- .github/workflows/coverage.yml
- .github/workflows/docs.yml
- .github/workflows/publish-android.yml
- .github/workflows/publish-jvm.yml
- .github/workflows/publish-swift.yml
- .github/workflows/publish-wasm.yml
- .github/workflows/rust.yml
- crypto-ffi/Cargo.toml
- crypto-ffi/Makefile.toml
- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto-ffi/bindings/js/jest.config.js
- crypto-ffi/bindings/js/rollup.config.js
- crypto-ffi/bindings/js/rollup.config.test.js
- crypto-ffi/bindings/js/test/CoreCrypto.test.js
- crypto-ffi/bindings/js/test/setup.js
- crypto-ffi/bindings/js/tsconfig.json
- crypto-ffi/src/generic.rs
- crypto-ffi/src/lib.rs
- crypto-ffi/src/wasm.rs
- crypto/src/error.rs
- crypto/src/test_utils/proteus_utils.rs
- keystore/src/proteus.rs
- package.json
Because rc5 is botched
The issue was basically that the implemented system was not working - at all.
* The use of the `?` operator in Rust short-circuits code execution, so the current code was unable to save the Proteus error codes aside - as we used a `match` statement to retrieve and query the error for its code.
* A fix for this was to instead "localize" the short-circuiting by wrapping our proteus code in IIFEs (Immediately Invoked Function Expressions) or IICs (Immediately Invoked Closure) for Rust-specific lingo. This allows us to retrieve the Error as-is and inspect it.
* The extended JS `Error` instance in Rust was a good idea, unfortunately it's 100% unsupported by the current tooling (`wasm_bindgen` namely). 
* So I had the idea to instead serialize a "rich error" to JSON, pass …
> hotfix: 0.6.0-rc6 [CL-129]

- kotlin/jvm/build.gradle.kts
----
----
JVM package of core crypto is broken
The sources and resources were configured incorrectly and thus empty Jars were produced.
Fix Gradle setup
----
----
----
> fix: publishing for JVM generating empty artifacts

- CHANGELOG.md
- CHANGELOG.tpl
- crypto-ffi/src/generic.rs
- crypto-ffi/src/wasm.rs
- crypto/Cargo.toml
- crypto/benches/public_group_state.rs
- crypto/src/group_store.rs
- crypto/src/lib.rs
- crypto/src/mls/conversation/decrypt.rs
- crypto/src/mls/conversation/durability.rs
- crypto/src/mls/conversation/encrypt.rs
- crypto/src/mls/conversation/export.rs
- crypto/src/mls/conversation/handshake.rs
- crypto/src/mls/conversation/merge.rs
- crypto/src/mls/conversation/mod.rs
- crypto/src/mls/conversation/renew.rs
- crypto/src/mls/external_commit.rs
- crypto/src/mls/external_proposal.rs
- crypto/src/mls/mod.rs
- crypto/src/mls/proposal.rs
- crypto/src/proteus.rs
- crypto/src/test_utils/central.rs
- interop/src/clients/corecrypto/native.rs
- interop/src/main.rs
- keystore/Cargo.toml
- keystore/src/connection/mod.rs
- keystore/src/lib.rs
Our previous `HashMap`-based cache could grow indefinitely in the case of massive accounts with many, many groups/conversations, each containing a ton of clients. This replaces this memory store by a LRU cache having the following properties: 
* Limited by number of entries AND occupied memory
* Defaults for memory: All the available system memory on other platforms / 100MB on WASM
* Defaults for number of entries: 
* 100 MLS groups
* 200 Proteus sessions
* Flow for retrieving a value
1. Check the LRU store if the value exists, if yes, it's promoted as MRU (Most Recently Used) and returned
2. If not found, it might have been evicted, so we search the keystore
3. If found in the keystore, the value is placed as MRU and returned
* Special case: we evict the store as much as needed to fit …
> feat!: Improve memory efficiency

- crypto/src/mls/conversation/commit_delay.rs
- crypto/src/mls/conversation/decrypt.rs
This is a commit delay optimization to avoid situations where both statements are true:
* The self client is the group creator. (leaf index = 0)
* The self client is being removed from the group in a proposal. This usually results in unusally high commit delays for other members from the sole virtue of a member with a lower leaf index being removed giving them a high position, thus a high commit delay (15s+)
> fix: Exclude self from self-remove-commit delay [CL-144]

- crypto/Cargo.toml
- mls-provider/Cargo.toml
----
----
Enable the `ios-wal-compat` feature for ios builds
----
> fix: enable ios-wal-compat for iOS builds by default [CL-146]

- crypto/src/proteus.rs
- keystore/Cargo.toml
- keystore/src/entities/proteus.rs
- keystore/src/error.rs
In case of "gaps" in the prekey id sequence, the previous algorithm (using the number of prekeys stored) would return the same ID over and over.
As a consequence, the same prekey id would be overwritten over and over.
> fix: Proteus auto prekey ids not incrementing [CL-150]

- package.json
----
----
The path to typescripts types in the package.json has the wrong file extension. This causes the `dukat` tool for generating Kotlin bindings to fail.
Change extension to `.ts`
----
----
----
> fix: typescript path has the wrong file extension

- kotlin/android/build.gradle.kts
----
----
The published android package didn't include the necessary native libraries.
Gradle misconfiguration 
Add dependency on copying native libraries before processing the JNI resources.
----
----
----
> fix: native libraries not included in android package

- Cargo.toml
- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto-ffi/bindings/js/test/CoreCrypto.test.js
- crypto-ffi/bindings/kt/main/com/wire/crypto/CoreCrypto.kt
- crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
- crypto-ffi/bindings/swift/lib/core_cryptoFFI.h
- crypto-ffi/src/CoreCrypto.udl
- crypto-ffi/src/generic.rs
- crypto-ffi/src/wasm.rs
- crypto/Cargo.toml
- crypto/src/e2e_identity/mod.rs
- crypto/src/e2e_identity/types.rs
- interop/src/clients/corecrypto/e2ei.js
----
----
In order to verify the issuers of the dpop & oidc proofs, clients would better use the "target" field in ACME challenges because it will be verified by the ACME server when validating the challenges
----
> feat!: support & expose "target" in ACME challenges [FS-910]

- Cargo.toml
- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto-ffi/bindings/kt/main/com/wire/crypto/CoreCrypto.kt
- crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
- crypto-ffi/bindings/swift/lib/core_cryptoFFI.h
- crypto-ffi/src/CoreCrypto.udl
- crypto-ffi/src/generic.rs
- crypto-ffi/src/wasm.rs
- crypto/src/e2e_identity/mod.rs
- crypto/src/e2e_identity/types.rs
----
----
URLs from order verification and finalize weren't returned anymore causing the API not to be usable without manually parsing json responses
----
> fix: return order & finalize url

- crypto-ffi/bindings/kt/main/com/wire/crypto/CoreCrypto.kt
- crypto-ffi/bindings/kt/main/com/wire/crypto/client/CoreCryptoCentral.kt
- crypto-ffi/bindings/kt/main/com/wire/crypto/client/MLSClient.kt
- crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
- crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
- crypto-ffi/bindings/swift/lib/core_cryptoFFI.h
- crypto-ffi/src/CoreCrypto.udl
- crypto-ffi/src/generic.rs
----
----
usize to u64 conversion error on Android in `client_valid_keypackages_count`. Whatever the reason this applies a default meaningful value
----
> fix: usize to u64 conversion error on Android [CL-170]

- crypto/src/error.rs
- crypto/src/mls/conversation/config.rs
- crypto/src/mls/conversation/decrypt.rs
----
----
Returns a specialised error when trying to decrypt a message encrypted on a older than 2 epochs.
----
> fix: Return specialised error when the epoch from the message is past the config's value - WPB-1179

- crypto-ffi/Makefile.toml
----
----
`ios-create-xcframework` task fails
Fix typo
----
----
----
> fix: typo in build xcframework task

- .github/workflows/publish-android.yml
- .github/workflows/publish-jvm.yml
- kotlin/android/build.gradle.kts
- kotlin/android/gradle.properties
- kotlin/build.gradle.kts
- kotlin/gradle.properties
- kotlin/gradle/wrapper/gradle-wrapper.properties
- kotlin/jvm/build.gradle.kts
- kotlin/jvm/gradle.properties
----
----
We want to publish to Sonatype & Maven Central instead of GitHub Packages in order to be compatible with f-droid.
- Configure the https://vanniktech.github.io/gradle-maven-publish-plugin plugin
- Update GitHub publish workflows
The credentials and signing keys are can either be configured in your gradle user's private `gradle.properties`:
```
mavenCentralUsername=<username>
mavenCentralPassword=<password>
signing.keyId=<pgp_key_id>
signing.password=<pgp_key_passphrase>
signing.secretKeyRingFile=<path/to/.gnupg/secring.gpg>
```
Or via environment variables:
```
ORG_GRADLE_PROJECT_sonatypePassword
ORG_GRADLE_PROJECT_sonatypeUsername
ORG_GRADLE_PROJECT_signingInMemoryKeyId
ORG_GRADLE_PROJECT_signingInMemoryKey …
```
> feat: publish to Sonatype instead of Github Packages

- crypto-ffi/src/CoreCrypto.udl
- crypto/src/error.rs
- crypto/src/mls/conversation/decrypt.rs
- crypto/src/mls/conversation/duplicate.rs
- crypto/src/mls/conversation/handshake.rs
- crypto/src/mls/conversation/mod.rs
- crypto/src/test_utils/fixtures.rs
----
----
To prevent clients from failing with decryption errors whenever a message is replayed by the server.
**THIS DOES NOT DETECT DUPLICATES ACROSS EPOCHS ! It just does so for incoming messages with epoch == current_epoch - 1**
**This also does not work when handshake messages are encrypted (which we do not do ATM and probably never will)**
How it works:
* commits: compute the local group `ConfirmationTag` and compare it with the commit's one
* proposals: compare the proposal with the ones in store
* application message: just change the openmls error mapping 
----
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the …
> feat!: catch duplicate messages [WPB-2788]

- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto-ffi/bindings/kt/main/com/wire/crypto/client/MLSClient.kt
- crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
- crypto-ffi/src/CoreCrypto.udl
- crypto-ffi/src/generic.rs
- crypto-ffi/src/wasm.rs
- crypto/Cargo.toml
- crypto/src/error.rs
- crypto/src/lib.rs
- crypto/src/mls/conversation/config.rs
- crypto/src/mls/conversation/decrypt.rs
- crypto/src/mls/conversation/handshake.rs
- crypto/src/mls/conversation/mod.rs
- crypto/src/mls/conversation/welcome.rs
- crypto/src/mls/credential/mod.rs
- crypto/src/mls/credential/trust_anchor.rs
- crypto/src/mls/external_commit.rs
- crypto/src/test_utils/central.rs
- crypto/src/test_utils/mod.rs
- crypto/src/test_utils/x509.rs
----
----
Include certificate roots and certificate policy in GroupContext and expose to API
----
> feat: Include certificate roots and certificate policy in GroupContext - WPB-1188

- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto-ffi/bindings/kt/main/com/wire/crypto/client/CoreCryptoCentral.kt
- crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
- crypto-ffi/src/generic.rs
- crypto-ffi/src/wasm.rs
- crypto/src/e2e_identity/rotate.rs
----
----
Expose 'ClientId' in e2ei methods for credential rotation since the e2ei client identifier differs from the one used in MLS
----
> feat!: expose 'ClientId' in e2ei methods

- crypto-ffi/src/wasm.rs
----
----
`e2ei_rotate_all` was returning `undefined` on Web
----
> fix: `e2ei_rotate_all` was returning 'undefined' on WASM

- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto-ffi/bindings/kt/main/com/wire/crypto/client/MLSClient.kt
- crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
- crypto-ffi/src/generic.rs
- crypto-ffi/src/wasm.rs
- crypto/src/e2e_identity/enabled.rs
- crypto/src/e2e_identity/mod.rs
----
----
Add `e2ei_is_enabled` for clients to spot if their MLS client is enrolled for end-to-end identity
----
> feat: add `e2ei_is_enabled` [WPB-3260]

- crypto/src/e2e_identity/rotate.rs
- crypto/src/mls/conversation/handshake.rs
- crypto/src/test_utils/central.rs
> test: add a roundtrip test for e2ei credential rotation to tackle a false positive regression

- crypto-ffi/bindings/kt/main/com/wire/crypto/client/CoreCryptoCentral.kt
- crypto-ffi/bindings/kt/test/com/wire/crypto/client/MLSClientTest.kt
- crypto-ffi/bindings/kt/test/com/wire/crypto/client/ProteusClientTest.kt
----
----
Kotlin wrapper tests were not compiling after the UniFFI upgrade which made most method suspendible.
- Wrap tests in `runTest  {}` to which runs the test inside a coroutine scope.
- Wrap `createClient` in `runBlocking`, we could also market he function as  `suspend` but currently that makes the tests hang, maybe because of https://github.com/mozilla/uniffi-rs/issues/1669
Disabled `e2ei()` since it hangs.
----
----
----
> fix: kotlin tests not compiling after methods became async

- crypto/src/mls/conversation/config.rs
- crypto/src/mls/conversation/decrypt.rs
----
----
Client `max_past_epoch` should be backend's one + 1 since there might be unordered messages. Also removed a useless check
----
> feat: adjust max past epoch [WPB-505]

- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto-ffi/bindings/kt/main/com/wire/crypto/client/MLSClient.kt
- crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
- crypto-ffi/src/CoreCrypto.udl
- crypto-ffi/src/generic.rs
- crypto-ffi/src/wasm.rs
- crypto/src/error.rs
- crypto/src/mls/conversation/buffer_messages.rs
- crypto/src/mls/conversation/decrypt.rs
- crypto/src/mls/conversation/handshake.rs
- crypto/src/mls/conversation/merge.rs
- crypto/src/mls/conversation/mod.rs
----
----
Regular group members were also impacted by unordered messages. As a consequence, messages from future epochs are now buffered.
* `decryptMessage` might throw a `BufferedFutureMessage` error which you should catch & ignore
* `commitAccepted` now returns an optional list of decrypted messages
----
> feat!: buffer messages from future epochs [WPB-3786]

- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/MLSClient.kt
- crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/MlsModel.kt
- crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
- crypto-ffi/src/CoreCrypto.udl
- crypto-ffi/src/generic.rs
- crypto-ffi/src/wasm.rs
- crypto/Cargo.toml
- crypto/src/lib.rs
- crypto/src/mls/buffer_external_commit.rs
- crypto/src/mls/conversation/buffer_messages.rs
- crypto/src/mls/conversation/db_count.rs
- crypto/src/mls/conversation/decrypt.rs
- crypto/src/mls/conversation/handshake.rs
- crypto/src/mls/conversation/merge.rs
- crypto/src/mls/conversation/self_commit.rs
- crypto/src/mls/credential/trust_anchor.rs
- crypto/src/mls/external_commit.rs
- crypto/src/mls/external_proposal.rs
----
----
The issue can of course also happen for receivers. Previous PR #383  was only considering the sender
----
> feat!: also restore buffered messages on the receiver side [WPB-3786]

- crypto-ffi/Cargo.toml
Given a `uniffi_core_crypto_ffi_fn_init_callback_corecryptocallbacks` symbol in the .so library, UniFFI was calling a
`uniffi_CoreCrypto_fn_init_callback_corecryptocallbacks` symbol in the bindings, leading to an issue where the actual generated code would crash when calling unknown symbols. This fixes that behavior by using a fixed branch of UniFFI
> fix: Make UniFFI produce the correct symbol in bindings

- Cargo.toml
- crypto/benches/utils/mls.rs
- crypto/src/error.rs
- crypto/src/mls/client/key_package.rs
- crypto/src/mls/client/mod.rs
- crypto/src/mls/conversation/config.rs
- crypto/src/mls/conversation/handshake.rs
- crypto/src/mls/conversation/leaf_node_validation.rs
- crypto/src/mls/conversation/mod.rs
- crypto/src/mls/conversation/renew.rs
- crypto/src/mls/credential/ext.rs
- crypto/src/mls/external_commit.rs
- crypto/src/mls/member.rs
- crypto/src/mls/proposal.rs
- crypto/src/test_utils/central.rs
----
----
Implement [RFC 9420 7.3](https://www.rfc-editor.org/rfc/rfc9420.html#name-leaf-node-validation)
* fix: generated LeafNodes capabilities as per spec /!\ Not backward compatible now that LeafNode validation in place
* fix: also fixes explicit updates (used in credential rotation) where LeafNode was not automatically rekeyed. No it is i.e. every update makes sure a new encryption key is created and replaces the previous one for the updated member.
----
> feat!: add LeafNode validation [WPB-3731]

- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/MLSClient.kt
- crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/MlsModel.kt
- crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
- crypto-ffi/src/generic.rs
- crypto-ffi/src/wasm.rs
- crypto/Cargo.toml
- crypto/src/e2e_identity/conversation_state.rs
- crypto/src/e2e_identity/device_status.rs
- crypto/src/e2e_identity/identity.rs
- crypto/src/e2e_identity/mod.rs
- crypto/src/e2e_identity/rotate.rs
- crypto/src/error.rs
- crypto/src/lib.rs
- crypto/src/mls/client/mod.rs
- crypto/src/mls/client/user_id.rs
- crypto/src/mls/conversation/export.rs
- crypto/src/mls/conversation/mod.rs
- crypto/src/mls/conversation/self_commit.rs
- crypto/src/test_utils/central.rs
- crypto/src/test_utils/mod.rs
- extras/wasm-browser-run/src/webdriver.rs
----
----
* ~~`get_user_identities`~~ becomes `get_device_identities` and a new `get_user_identities` added to list identities in a group belonging to the same user
* handle is format changed from `im:wireapp={input}` to `im:wireapp=%40{input}@{domain}`
* WireIdentity contains JWK thumbprint of the certificate public key
* WireIdentity contains a validation status (Valid/Expired/Revoked)
----
> feat!: e2ei changes [WPB-5470] [WPB-5473]

- CHANGELOG.md
- CHANGELOG.tpl
- crypto-attributes/Cargo.toml
- crypto-ffi/Cargo.toml
- crypto-ffi/bindings/gradle.properties
- crypto/Cargo.toml
- interop/Cargo.toml
- keystore-dump/Cargo.toml
- keystore/Cargo.toml
- mls-provider/Cargo.toml
- package.json
> build: release v1.0.0-rc.20

- crypto-ffi/Cargo.toml
- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto-ffi/bindings/js/test/CoreCrypto.test.js
- crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/CoreCryptoCentral.kt
- crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/MLSClient.kt
- crypto-ffi/bindings/jvm/src/test/kotlin/com/wire/crypto/client/E2EITest.kt
- crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
- crypto/Cargo.toml
- crypto/src/e2e_identity/conversation_state.rs
- crypto/src/e2e_identity/id.rs
- crypto/src/e2e_identity/identity.rs
- crypto/src/e2e_identity/mod.rs
- crypto/src/e2e_identity/rotate.rs
- crypto/src/e2e_identity/stash.rs
- crypto/src/mls/client/identifier.rs
- crypto/src/mls/client/mod.rs
- crypto/src/mls/conversation/self_commit.rs
- crypto/src/mls/credential/mod.rs
- crypto/src/mls/credential/x509.rs
- crypto/src/mls/mod.rs
- crypto/src/proteus.rs
- crypto/src/test_utils/central.rs
- crypto/src/test_utils/mod.rs
- mls-provider/src/crypto_provider.rs
----
----
So far regular supplied ClientId in MLS had their UserId portion encoded with the UUIDv4 hyphenated string representation whereas in e2ei certificate the uint128 base64UrlUnpadded representation was used. This tends to harmonize this.
From now on only the former format will surface in the public API so users won't be confused anymore.
----
> feat!: canonicalize ClientId [WPB-5608]

- crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
> fix: Swift wrapper for E2eiEnrollment was not used in other methods

- crypto-ffi/src/wasm.rs
> fix: null pointer in Javascript

- Cargo.toml
- crypto-ffi/bindings/js/test/CoreCrypto.test.js
- crypto-ffi/bindings/jvm/src/test/kotlin/com/wire/crypto/client/E2EITest.kt
- crypto/Cargo.toml
- crypto/src/e2e_identity/mod.rs
- crypto/src/e2e_identity/rotate.rs
- crypto/src/mls/client/user_id.rs
- crypto/src/test_utils/central.rs
> feat: ClientId & Handle are URIs

- crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/E2eiClient.kt
- crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
- crypto-ffi/src/generic.rs
- crypto-ffi/src/wasm.rs
- crypto/src/e2e_identity/mod.rs
- crypto/src/e2e_identity/types.rs
----
----
Return keyauth after creating the authorization to seal it in the OIDC Id token.
----
> feat!: expose keyauth in ACME authz

- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto-ffi/bindings/js/test/CoreCrypto.test.js
- crypto-ffi/src/wasm.rs
- crypto/src/e2e_identity/mod.rs
- crypto/src/e2e_identity/rotate.rs
- crypto/src/e2e_identity/stash.rs
----
----
remove refreshToken handling from WASM altogether as it is not used and tentatively fix an issue with CoreCrypto's PkiEnv being dropped.
----
> feat(e2ei)!: rework refreshToken

- crypto/src/e2e_identity/init_certificates.rs
- crypto/src/e2e_identity/mod.rs
- crypto/src/mls/mod.rs
- crypto/src/mls/restore.rs
> fix: restore pki_env from disk whenever necessary

- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/CoreCryptoCentral.kt
- crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/E2EIModel.kt
- crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/MlsModel.kt
- crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
- crypto-ffi/src/generic.rs
- crypto-ffi/src/wasm.rs
- crypto/src/e2e_identity/init_certificates.rs
- crypto/src/e2e_identity/mod.rs
- crypto/src/e2e_identity/rotate.rs
- crypto/src/mls/credential/crl.rs
- crypto/src/test_utils/mod.rs
> fix(e2ei): register intermediate certificates at issuance since they're not fetchable afterwards

- crypto/src/mls/mod.rs
> fix: only restore PKI env if client is e2ei capable.

- .github/pull_request_template.md
Just a much smaller, more readable PR template.
> chore: .github: simplify the PR template

- crypto-ffi/Makefile.toml
- crypto-ffi/build.rs
On Android x86-64 we need to link the runtime lib statically because       
the compiler fails to do so due to -nodefaultlibs being given by           
default. This is not a problem on other Android platforms, though.         
More details at https://github.com/mozilla/application-services/issues/5436
> refactor: crypto-ffi: statically link the runtime lib via Makefile.toml [WPB-8945]

- .github/workflows/bindings.yml
- .github/workflows/coverage.yml
- .github/workflows/deny.yml
- .github/workflows/rust.yml
To guarantee we always have the CI run on the latest state on develop, we want to run the CI on pushes to develop, not just on PRs.
----
> chore: run ci on pushes to dev as well

- crypto/src/mls/credential/mod.rs
To fix the failing tests in CI, we pin the future to heap in test with overflowing stack
----
> test: pin future to heap in test with overflowing stack [WPB-9543]

- crypto/src/mls/external_proposal.rs
- keystore/src/mls.rs
The original tests were most likely removed as part of 4e7d907663026b74484b37942c7ac4cfb1ff6cf9 by mistake. So bring them back, and adjust for the API changes done since then.
----
> test: crypto: bring back external remove proposal tests (WPB-9184)

- crypto-ffi/src/generic.rs
This documents a change that was done in https://github.com/wireapp/core-crypto/commit/39e14031a3fa696cb8f28b3e0a1d3e366814a558.
----
> chore: document compliance with newest uniffi update [WPB-9588]

- crypto-ffi/Cargo.toml
- crypto-ffi/src/generic.rs
- crypto-ffi/src/wasm.rs
This changes the log output format to JSON.
----
> fix: change the log output to json

- .cargo/config.toml
- support/android/libgcc.a
It was added in 5eb47aeb9599346bf3f04138fbf7439bcda662fc, however there's no good explanation for it. Let's try to get rid of it.
----
> chore: remove support/android/libgcc.a

- Cargo.toml
- crypto/Cargo.toml
- mls-provider/Cargo.toml
> chore: Cargo.toml: convert wire-e2e-identity to a workspace dependency

- Cargo.toml
- crypto/Cargo.toml
- crypto/src/proteus.rs
- keystore/Cargo.toml
- keystore/src/connection/platform/wasm/storage.rs
- keystore/src/entities/platform/wasm/mls/credential.rs
- keystore/src/mls.rs
The upstream has just released 0.6.1 that with https://github.com/devashishdxt/rexie/pull/26, 
which we needed, so we can now track upstream.                                                
----
> chore: go back to upstream rexie

- Cargo.toml
- crypto/Cargo.toml
- deny.toml
- mls-provider/Cargo.toml
Upstream has made a fix and released a new version of der_derive: https://github.com/RustCrypto/formats/pull/1443
----
> chore: remove dependency on a fork of RustCrypto/formats

- Cargo.toml
- crypto/Cargo.toml
- crypto/src/group_store.rs
The fork was originally intended to provide try_insert, which doesn't modify the underlying map, however, the implementation is broken (see https://github.com/koute/schnellru/pull/2) and it doesn't fit the current semantics of schnellru.
----
> chore: crypto: drop our fork of schnellru

- crypto-ffi/Makefile.toml
It's unused and we don't have the sample project anymore.
----
> chore: crypto-ffi: remove setup-sample-project task from Makefile.toml

- .github/workflows/benchmarks.yml
> ci: enable commit sha reference for PR benchmarks

- crypto/src/mls/conversation/decrypt.rs
- crypto/src/mls/conversation/mod.rs
- crypto/src/mls/conversation/own_commit.rs
See corresponing jira item
----
> fix: handle own commit after mls error [WPB-10105]

- crypto-ffi/Makefile.toml
Similar to cb5f5c7f02df17fbeab94801f060fc2e6fb2d165, it turns out that on i686-linux-android the compiler fails to link the runtime library, resulting in errors like
java.lang.UnsatisfiedLinkError: Unable to load library 'core_crypto_ffi':
dlopen failed: cannot locate symbol "__atomic_load_8" referenced by ...
So let's do it manually.
> build: fix dynamic linker error on i686-linux-android [WPB-10493]

- crypto-ffi/src/generic.rs
"Use of map over inspect", which came up with the release of Rust 1.81.
See above
----
> style: fix new clippy lint

- .gitignore
- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/MLSClient.kt
- crypto-ffi/src/generic.rs
- crypto-ffi/src/wasm.rs
- crypto/src/e2e_identity/conversation_state.rs
- crypto/src/e2e_identity/rotate.rs
- crypto/src/mls/conversation/own_commit.rs
Expose API for upgrading from basic to x509 credentials for a conversation. This is useful for a clients to address the race condition, which can happen if they got added to a conversation with their basic credentials while upgrading to x509 credentials. 
----
> feat: expose API for upgrading from basic to x509 credentials for a conversation WPB-10161

- Cargo.lock
- Cargo.toml
- decode/Cargo.toml
- decode/README.md
- decode/src/main.rs
Adding a cli tool for decoding & pretty printing various wire formats of Proteus and MLS.
----
> feat: add decode cli tool WPB-11840

- .github/workflows/benchmarks.yml
Apparently, due to a breaking change in the bencher cli, thresholds were not applied.
See above
----
> ci: copy bencher thresholds from main to feature branch

- crypto-ffi/bindings/jvm/src/test/kotlin/com/wire/crypto/client/E2EITest.kt
- crypto-ffi/bindings/jvm/src/test/kotlin/com/wire/crypto/client/MLSTest.kt
Kotlin apparently lets users name functions with arbitrary strings,
as long as they are enclosed with backticks. Unfortunately, this
feature is apparently not supported in the Android version of the JVM,
causing the test suite to fail to run on Android.
A brief examination of peer repositories maintained by Wire suggests
that arbitrary-string function names are unusual. So to enable the
Kotlin test suite to potentially run on Android, this PR renames
all affected functions.
----
> fix: avoid spaces in kotlin test names

- crypto/benches/utils/mls.rs
- crypto/src/context.rs
- crypto/src/e2e_identity/conversation_state.rs
- crypto/src/e2e_identity/enabled.rs
- crypto/src/e2e_identity/mod.rs
- crypto/src/e2e_identity/rotate.rs
- crypto/src/mls/client/identities.rs
- crypto/src/mls/client/key_package.rs
- crypto/src/mls/client/mod.rs
- crypto/src/mls/conversation/buffer_messages.rs
- crypto/src/mls/conversation/commit.rs
- crypto/src/mls/conversation/config.rs
- crypto/src/mls/conversation/decrypt.rs
- crypto/src/mls/conversation/encrypt.rs
- crypto/src/mls/conversation/mod.rs
- crypto/src/mls/conversation/proposal.rs
- crypto/src/mls/conversation/renew.rs
- crypto/src/mls/external_commit.rs
- crypto/src/mls/external_proposal.rs
- crypto/src/mls/mod.rs
- crypto/src/mls/proposal.rs
- crypto/src/test_utils/context.rs
- crypto/src/test_utils/mod.rs
> refactor: keep client initialization state internal [WPB-12004]

- Cargo.lock
- Cargo.toml
- crypto-ffi/Cargo.toml
- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto-ffi/bindings/js/test/CoreCrypto.test.ts
- crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/CoreCryptoCentral.kt
- crypto-ffi/src/generic/mod.rs
- crypto-ffi/src/wasm/mod.rs
Support changing loggers and max log level at runtime.
also renamed `initLogger` in the bindings to `setLogger` since IMO init is not suitable anymore
when we allow replacing a logger.
----
> feat: support changing loggers at runtime WPB-11541

- .cargo/config.toml
- .github/workflows/bindings.yml
- .github/workflows/publish-android.yml
- README.md
- crypto-ffi/Makefile.toml
- crypto-ffi/bindings/android/build.gradle.kts
Drop support for `i686-linux-android` target
----
> build: drop i686-linux-android target [WPB-10568]

- crypto/src/error.rs
- crypto/src/mls/conversation/decrypt.rs
`WrongEpoch` used to be emitted both when the message epoch was too old to handle, and when it was too far in the future to handle. That could lead to client inefficiencies when handling this error.
Split it into `StaleMessage` and `UnbufferedFutureMessage` to distinguish these cases.
----
> feat: disambiguate `WrongEpoch` [WPB-14351]

- .pre-commit-config.yaml
- Cargo.lock
- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto-ffi/bindings/js/test/CoreCrypto.test.ts
- crypto-ffi/bindings/jvm/src/test/kotlin/com/wire/crypto/client/GeneralTest.kt
- crypto-ffi/src/generic/mod.rs
- crypto-ffi/src/wasm/mod.rs
- crypto/Cargo.toml
- crypto/build.rs
- crypto/src/build_metadata.rs
- crypto/src/lib.rs
Adds publicly-visible build metadata to `core-crypto` and exposes it via FFI.
----
> feat: add public build metadata [WPB-11001]

- Cargo.lock
- Cargo.toml
- crypto-ffi/Cargo.toml
- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto-ffi/bindings/js/test/CoreCrypto.test.ts
- crypto-ffi/src/generic/mod.rs
- crypto-ffi/src/wasm/mod.rs
- crypto/Cargo.toml
- crypto/src/lib.rs
- crypto/src/mls/conversation/decrypt.rs
- crypto/src/obfuscate.rs
* Change the logging system to support structured data
* Add debug logs for the decryption path in MLS and include relevant contextual information when available.
----
> feat: structured logging [WPB-11544]

- Cargo.lock
- Cargo.toml
- crypto/src/e2e_identity/conversation_state.rs
- crypto/src/mls/credential/mod.rs
- crypto/src/mls/credential/x509.rs
- crypto/src/test_utils/x509.rs
While updating to rusty-jwt-tools 0.11., we encountered failings tests due to
- version 0.11 correctly doing certificate validation (this was not the case before)
- incorrect construction of `CertificateBundle` instances, which were missing intermediate CA's certificate
This PR fixes the latter.
> chore: update rusty-jwt-tools to latest release, 0.11.0

- keystore/Cargo.toml
- keystore/src/transaction/mod.rs
An empty transaction could be an indication that the app consuming core crypto contains a programming error.
----
> chore: log a warning when an empty transaction is committed [WPB-11743]

- crypto-ffi/bindings/js/test/CoreCrypto.test.ts
- crypto-ffi/src/wasm/mod.rs
- change test for build metadata to achieve closer parity with the kotlin test.
- change fields of BuildMetadata to camelCase.
- To comply to javascript conventions.
- This is desirable because we expose this struct beyond our typescript wrapper.
- It has to be this tedious way of renaming each field separately, until rustwasm/wasm-bindgen#1818 is solved.
----
> refactor: change test for build meta data

- .github/workflows/bindings.yml
- .github/workflows/docs.yml
- README.md
- crypto-ffi/Makefile.toml
- interop/src/build/web/wasm.rs
- ci: use bun instead of npm when building
- ci: make sure targets are built before building docs
----
> ci: fix doc generation

- .github/workflows/bindings.yml
- .github/workflows/docs.yml
- .github/workflows/publish-wasm.yml
- Cargo.lock
- crypto/Cargo.toml
- crypto/src/error.rs
The old error swallowed the underlaying indexdb error.
----
> fix: improve errors when hitting an indexdb error during cryptobox migration

- crypto/src/mls/conversation/decrypt.rs
Proposal and commit messages should be very useful and infrequent enough that we can log them by default.
----
> chore: log proposal & commit message using info

- crypto-ffi/bindings/js/test/CoreCrypto.test.ts
- crypto-ffi/src/generic/mod.rs
- crypto-ffi/src/wasm/context/mod.rs
- crypto-ffi/src/wasm/mod.rs
We started to bundle together errors which clients can't act upon, but it's still useful to include source error message for debugging purposes.
----
> feat: include the message of the source error when bundling errors together [WPB-14614]

- crypto/src/mls/external_commit.rs
Mls group insertion and deletion of the pending group is transactional since 427e0e0b65dca3b2dce006e4e1aa4da1cf1f9c3c.
----
> chore: remove stale todo comment [WPB-9595]

- Cargo.lock
- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto-ffi/bindings/js/test/utils.ts
- crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/CoreCrypto.kt
- crypto-ffi/src/generic/mod.rs
- crypto-ffi/src/wasm/mod.rs
- crypto/src/mls/mod.rs
- interop/Cargo.toml
- interop/src/clients/corecrypto/ffi.rs
- interop/src/clients/corecrypto/native.rs
- interop/src/clients/corecrypto/web.rs
- interop/src/clients/cryptobox/native.rs
- interop/src/clients/cryptobox/web.rs
- interop/src/clients/mod.rs
- interop/src/main.rs
- mls-provider/src/lib.rs
Stop exposing `wipe()` and `unload()`
Clients should instead call close() which will close the  database connection, it's then safe to delete the core crypto database.
----
> fix: stop exposing wipe() and unload() since they are broken in Kotlin [WPB-14514]

- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto-ffi/bindings/js/CoreCryptoContext.ts
- crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/CoreCrypto.kt
- crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/CoreCryptoContext.kt
- crypto-ffi/bindings/jvm/src/test/kotlin/com/wire/crypto/MLSTest.kt
- crypto-ffi/src/generic/context/proteus.rs
- crypto-ffi/src/generic/mod.rs
- crypto-ffi/src/wasm/context/proteus.rs
- crypto-ffi/src/wasm/mod.rs
- crypto/benches/utils/proteus_bench.rs
- crypto/src/proteus.rs
- interop/src/clients/corecrypto/ffi.rs
- interop/src/clients/corecrypto/native.rs
- interop/src/main.rs
- keystore/src/connection/mod.rs
- keystore/src/transaction/mod.rs
Previously, an error was thrown when a new transaction was started and there was one in progress. This was not the intended behavior.
See above
----
> fix: wait for current transaction to finish when creating a new one

- crypto-ffi/src/generic/mod.rs
When creating transaction we also create an in-memory database as cache. When this database is created all the schema migration are performed and logged at the info level and they are very verbose. Silence them by mapping these logs to the Debug level instead.
----
> fix: silence verbose logs when performing a transaction [WPB-14953]

- crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/CoreCryptoException.kt
- crypto-ffi/src/generic/mod.rs
- crypto-ffi/src/wasm/mod.rs
Turns out that clients _do_ care about this error variant, so let's give it back to them.
----
> feat!(ffi/error): expose `OrphanWelcome` to clients [WPB-14954]

- crypto-ffi/Makefile.toml
- crypto-ffi/bindings/js/test/tsc-import-test.ts
- crypto-ffi/bindings/js/wdio.conf.ts
- keystore/src/connection/platform/wasm/migrations/keystore_v_1_0_0/connection/platform/wasm/storage.rs
- keystore/src/connection/platform/wasm/storage.rs
An assortment of minor cleanups and a fix that removes `debug_assert!` calls from the memory keystore, which were breaking web tests and were there without a good reason.
> chore: remove debug_assert! calls from mem keystore [WPB-14558]

- crypto-ffi/Cargo.toml
- crypto/src/mls/conversation/own_commit.rs
- keystore/src/connection/platform/generic/mod.rs
- keystore/src/connection/platform/wasm/storage.rs
With most new rustc versions come new lints. These are great, because they cause our codebase to gradually improve. But they necessitate commits like this from time to time where a lint got stricter.
Fix some lifetime style lints.
----
> chore: fix clippy warnings about needless lifetimes so CI can build cleanly again

- crypto-ffi/bindings/js/src/CoreCrypto.ts
- crypto-ffi/bindings/js/src/CoreCryptoContext.ts
- crypto-ffi/bindings/js/src/CoreCryptoInstance.ts
- crypto-ffi/bindings/js/src/CoreCryptoMLS.ts
- crypto-ffi/src/wasm/mod.rs
This PR is a continuation of the work done in https://github.com/wireapp/core-crypto/pull/848.
It resolves the remaining warnings about conflicting Typescript types and does it by eliminating wrapper types and instead only exposing types defined on the Rust level.
> refactor: rework JS wrapper, phase 2 [WPB-15318]

- crypto-ffi/bindings/js/src/CoreCryptoE2EI.ts
- crypto-ffi/bindings/js/src/CoreCryptoMLS.ts
- crypto-ffi/src/wasm/mod.rs
We reference non-existing items in JS docs, so just remove those.
> chore: fix few doc warnings

- .github/workflows/benchmarks.yml
- .github/workflows/bindings.yml
- .github/workflows/build-android.yml
- .github/workflows/build-jvm-linux.yml
- .github/workflows/coverage.yml
- .github/workflows/deny.yml
- .github/workflows/docs.yml
- .github/workflows/publish-android.yml
- .github/workflows/publish-jvm.yml
- .github/workflows/publish-swift.yml
- .github/workflows/publish-wasm.yml
- .github/workflows/rust.yml
> build: use reusable workflows in ci [WPB-14852]

- crypto/Cargo.toml
- keystore/Cargo.toml
- mls-provider/Cargo.toml
We had this already for the crypto-ffi crate, however, the warning still appeared for all other crates with wasm-bindgen tests.
See title
----
> chore: silence warning about unexpected cfg in wasm-bindgen everywhere

- crypto-ffi/bindings/js/src/CoreCrypto.ts
- crypto-ffi/bindings/js/src/CoreCryptoContext.ts
- crypto-ffi/bindings/js/src/CoreCryptoError.ts
- crypto-ffi/bindings/js/src/CoreCryptoInstance.ts
- crypto-ffi/bindings/js/src/CoreCryptoMLS.ts
- crypto-ffi/bindings/js/test/CoreCrypto.test.ts
- crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/CoreCryptoContext.kt
- crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/MlsModel.kt
- crypto-ffi/src/generic/mod.rs
- crypto-ffi/src/wasm/mod.rs
- crypto/src/lib.rs
- crypto/src/mls/external_commit.rs
> fix: fix typescript wrapper according to mls transport api changes [WPB-15407]

- Cargo.lock
- Cargo.toml
- crypto-ffi/Cargo.toml
- crypto-ffi/src/generic/mod.rs
- crypto-ffi/src/wasm/mod.rs
Adds a minor non-breaking feature which logs error messages just as they cross the FFI boundary.
----
> feat: log errors at ffi boundary [WPB-14355]

- .github/workflows/docs.yml
The github pages deployment was presumably broken because the upload-artifact action had a "merge multple" policy where the rust docs were overwriting the uploaded kotlin and typescript docs.
This renames the rust doc artifact and uploads it first so that it doesn't overwrite the kotlin and typescript docs anymore.
----
> docs: fix github pages deployment

- scripts/merge-pr.sh
We have decided to require both signed commits and a linear history in github, which breaks the github "merge" button completely.
This script does the right thing to accomplish signed commits with a linear history, because it's kind of a pain to do manually each time.
----
> build: add a script to merge a PR according to our current workflow

- crypto-ffi/bindings/js/src/CoreCrypto.ts
- crypto-ffi/bindings/js/src/CoreCryptoInstance.ts
- crypto-ffi/bindings/js/test/CoreCrypto.test.ts
Move the `version()` from the CoreCrypto instance to the module level.
----
> refactor: move version function to module [WPB-15329]

- scripts/merge-pr.sh
Turns out that shellcheck was right, and my bash-fu was weak. This now properly emits output to stderr instead of a file named `2`.
Also it now uses `printf` instead of `echo` so that things like `\n` work.
----
> fix: `merge-pr.sh` emits output when bailing out

- .github/workflows/publish-android.yml
- .github/workflows/publish-jvm.yml
- .github/workflows/publish-swift.yml
- .github/workflows/publish-wasm.yml
Make sure every tag has a signature. Note that we intentionally do not verify the signature, similarly for commits.
----
> ci: enforce signed tags

- scripts/update-versions.sh
We moved package.json from the top level and crypto-attributes was renamed, so make sure the script is up to date.
> chore: scripts: update update-versions.sh

- crypto-ffi/src/generic/mod.rs
- crypto-ffi/src/wasm/mod.rs
- crypto/src/mls/buffer_external_commit.rs
- crypto/src/mls/conversation/buffer_messages.rs
- crypto/src/mls/conversation/commit.rs
- crypto/src/mls/conversation/decrypt.rs
- crypto/src/mls/conversation/error.rs
We have observed some unexpected behaviour when restoring buffered proposals, so let's improve the logs.
----
> chore: improve logs when buffering messages

- .github/workflows/benchmarks.yml
- .github/workflows/bindings.yml
- .github/workflows/publish-wasm.yml
- .github/workflows/rust.yml
- crypto-ffi/Cargo.toml
- crypto-ffi/src/generic/mod.rs
- crypto-ffi/src/wasm/mod.rs
- crypto/src/error.rs
- crypto/src/mls/buffer_external_commit.rs
- crypto/src/mls/conversation/buffer_messages.rs
- crypto/src/mls/conversation/commit.rs
- crypto/src/mls/conversation/decrypt.rs
- crypto/src/mls/conversation/own_commit.rs
- extras/webdriver-installation/Cargo.toml
- keystore/src/connection/platform/generic/mod.rs
- keystore/src/connection/platform/wasm/storage.rs
> [3.x] chore: emit info log when buffering, restoring, or clearing future messages

- .github/workflows/publish-android.yml
- .github/workflows/publish-jvm.yml
- .github/workflows/publish-swift.yml
- .github/workflows/publish-wasm.yml
We need to have full tag objects in order to check for signature presence.
> chore: ci: fetch tag objects when checking out the repo for publishing

- .github/workflows/publish-android.yml
- .github/workflows/publish-jvm.yml
- .github/workflows/publish-swift.yml
- .github/workflows/publish-wasm.yml
actions/checkout is broken and 'fetch-tags: true' does not help
to fetch tag objects: https://github.com/actions/checkout/issues/290
So work around it by fetching tags manually.
> chore: ci: fetch tags manually

- .github/workflows/publish-android.yml
- .github/workflows/publish-jvm.yml
- .github/workflows/publish-swift.yml
- .github/workflows/publish-wasm.yml
Apparently,` ${{ github.ref }}` is the full ref name, starting with refs/, so implicit mapping won't work.
> chore: ci: specify full ref mapping

- CHANGELOG.md
- Cargo.lock
- crypto-attributes/Cargo.toml
- crypto-ffi/Cargo.toml
- crypto-ffi/bindings/gradle.properties
- crypto-ffi/bindings/js/CoreCrypto.ts
- crypto/Cargo.toml
- interop/Cargo.toml
- keystore-dump/Cargo.toml
- keystore/Cargo.toml
- mls-provider/Cargo.toml
- package.json
> release: v3.0.2

- .github/workflows/publish-android.yml
- .github/workflows/publish-jvm.yml
- CHANGELOG.md
The publishing task name was changed.
> chore: fix publishing, another try

- crypto-ffi/bindings/android/build.gradle.kts
The base plugin is missing tasks to publish to Maven Central. Instead, use the high-level plugin, that provides those tasks, but still try to disable javadoc generation.
For POM information it looks like the high-level plugin picks up gradle.properties automatically, so we can remove the
```
pomFromGradleProperties()
```
bit. Actually, we have to remove it, because it's incompatible with the high-level plugin and using it results in an error.
> chore: crypto-ffi: don't use the base maven-publish plugin

- crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/CoreCryptoException.kt
- crypto-ffi/src/generic/mod.rs
- crypto-ffi/src/wasm/mod.rs
- crypto/src/mls/conversation/buffer_messages.rs
- crypto/src/mls/conversation/decrypt.rs
- crypto/src/mls/conversation/error.rs
- crypto/src/test_utils/context.rs
- keystore/src/connection/platform/generic/migrations/V14__buffered_commits.sql
- keystore/src/connection/platform/wasm/migrations/mod.rs
- keystore/src/entities/mls.rs
- keystore/src/error.rs
- keystore/src/transaction/dynamic_dispatch.rs
After creating a test replicating [the 15810 scenario](https://wearezeta.atlassian.net/browse/WPB-15810). Turns out that one key issue was that clients who received a commit prior to a referenced proposal were just giving up. This PR fixes that issue by adding the capability to buffer one commit per conversation. When there is a buffered commit, it is re-attempted each time a proposal arrives until it succeeds.
Clients still need to watch out for desync! If the required proposal is simply never delivered, the client will lag behind until the epoch changes again, at which point they can prove desync. This fix solves everything under the hood, in the expected case that all messages are delivered, and reorderings don't delay any single message by more than a few seconds. 
----
- The **PR …
> feat: buffer commits until all required proposals have arrived [WPB-15810]

- Cargo.lock
- Cargo.toml
- crypto-ffi/Cargo.toml
- crypto-macros/Cargo.toml
- crypto/Cargo.toml
- crypto/src/error.rs
- crypto/src/mls/conversation/buffer_messages.rs
- crypto/src/mls/conversation/decrypt.rs
- decode/Cargo.toml
- extras/keystore-regression-versions/Cargo.toml
- extras/webdriver-installation/Cargo.toml
- interop/Cargo.toml
- keystore-dump/Cargo.toml
- keystore/Cargo.toml
- keystore/src/connection/platform/generic/migrations/V14__buffered_commits.sql
- keystore/src/connection/platform/wasm/migrations/mod.rs
- keystore/src/entities/mls.rs
- keystore/src/error.rs
- keystore/src/transaction/dynamic_dispatch.rs
- mls-provider/Cargo.toml
- Backports the commit-buffering mechanics from #907 to the 3.x branch.
- Closes #914
Should we make the unbuffered commit error public? On some target platforms, but not all, adding a variant to the error enum is a breaking change. 
If we decide to do this, we also need to cherry-pick fbb365facb794cb495f51515dfd9ca448f6d1845 into this PR.
----
> fix: backport commit buffering (attempt 4)

- CHANGELOG.md
> chore: update changelog for 3.1.0

- crypto-ffi/bindings/js/src/CoreCrypto.ts
- crypto-ffi/bindings/js/src/CoreCryptoInstance.ts
- crypto-ffi/bindings/js/test/CoreCrypto.test.ts
- crypto-ffi/src/wasm/context/e2ei.rs
- crypto-ffi/src/wasm/mod.rs
Querying an `WireIdentity` using `getDeviceIdentities` or `getUserIdentities` didn't return a type matching the declared `WireIdentity` and on top of that, the `WireIdentity` and `X509Identity` were not publicly exposed.
----
> fix: querying an wire identity is correctly typed in TS bindings [WPB-16047]

- crypto-ffi/Makefile.toml
When running uniffi-bindgen, we rely on the library that was just built for the purpose of linking uniffi-bindgen.
> chore: crypto-ffi: remove useless release-build task

- crypto/src/e2e_identity/identity.rs
- crypto/src/mls/conversation/conversation_guard.rs
- crypto/src/mls/conversation/export.rs
- crypto/src/mls/conversation/external_sender.rs
- crypto/src/mls/conversation/mod.rs
- crypto/src/mls/mod.rs
Start working on refactoring conversation methods so we don't have to duplicate the whole `Conversation` API on `CentralContext`.
----
> chore: implement `ConversationGuard` [WPB-15577]

- .github/workflows/bindings.yml
- .github/workflows/build-android.yml
- .github/workflows/build-ios.yml
- .github/workflows/build-jvm-linux.yml
- .github/workflows/publish-android.yml
- .github/workflows/publish-jvm.yml
- crypto-ffi/Makefile.toml
- crypto-ffi/src/generic/mod.rs
- crypto-ffi/src/wasm/context/proteus.rs
- crypto-ffi/src/wasm/mod.rs
- crypto/src/mls/conversation/commit_delay.rs
- interop/src/clients/corecrypto/ffi.rs
This PR splits parallelizes Android builds, and makes each target-specific job upload its own artifact.
A new job, `package-android` is introduced that waits for target-specific jobs to complete, generates
bindings and calls gradle to make the final package.
There are also a few smaller things like renaming of bindings-related tasks.
> chore: more CI improvements

- crypto-ffi/src/generic/context/mod.rs
- crypto-ffi/src/wasm/context/mod.rs
- crypto/benches/commit.rs
- crypto/benches/create_group.rs
- crypto/benches/mls_proteus.rs
- crypto/benches/utils/mls.rs
- crypto/src/e2e_identity/rotate.rs
- crypto/src/mls/buffer_external_commit.rs
- crypto/src/mls/conversation/buffer_messages.rs
- crypto/src/mls/conversation/commit.rs
- crypto/src/mls/conversation/commit_delay.rs
- crypto/src/mls/conversation/conversation_guard.rs
- crypto/src/mls/conversation/conversation_guard/commit.rs
- crypto/src/mls/conversation/conversation_guard/mod.rs
- crypto/src/mls/conversation/decrypt.rs
- crypto/src/mls/conversation/duplicate.rs
- crypto/src/mls/conversation/leaf_node_validation.rs
- crypto/src/mls/conversation/merge.rs
- crypto/src/mls/conversation/mod.rs
- crypto/src/mls/conversation/orphan_welcome.rs
- crypto/src/mls/conversation/proposal.rs
- crypto/src/mls/conversation/renew.rs
- crypto/src/mls/conversation/welcome.rs
- crypto/src/mls/external_commit.rs
- crypto/src/mls/external_proposal.rs
- crypto/src/mls/proposal.rs
- crypto/src/test_utils/context.rs
- interop/src/clients/corecrypto/native.rs
- interop/src/main.rs
> refactor: move commit-producing APIs to `ConversationGuard` [WPB-15587]

- .github/workflows/rust.yml
fix some (spurious!) CI failures when running wasm tests
----
> build: fix CI failures [WPB-16271]

- crypto-ffi/src/wasm/mod.rs
We don't use a stack protector so this symbol is not going to be used. Also, wasmer version 5.0.4 works just fine when inspecting the generated code.
> chore: crypto-ffi: remove __stack_chk_fail

- crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/CoreCrypto.kt
- crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/CoreCryptoContext.kt
- crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/E2EIEnrollment.kt
- crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/MlsModel.kt
- crypto-ffi/bindings/jvm/src/test/kotlin/com/wire/crypto/MLSTest.kt
don't expose uniffi types in the kotlin bindings
----
> fix: don't expose uniffi types in the kotlin bindings [WPB-16300]

- crypto/src/mls/conversation/conversation_guard/merge.rs
- crypto/src/mls/conversation/conversation_guard/mod.rs
- crypto/src/mls/conversation/decrypt.rs
- crypto/src/mls/conversation/duplicate.rs
- crypto/src/mls/conversation/merge.rs
- crypto/src/mls/conversation/own_commit.rs
> refactor: move `clear_pending_proposal`, `clear_pending_commit` to `ConversationGuard` [WPB-15588]

- .github/workflows/docs.yml
- docs/index.md
Add a landing page that links rust and bindings api documentations. Currently only for main, next, version-specific links are going to be added.
Docs landing page
----
> docs: add docs landing page [WPB-11382]

- .github/workflows/docs.yml
> ci: publish docs in separate directory when pushing a tag

- .github/workflows/docs.yml
> ci: keep old files when publishing docs

- docs/index.md
Jekyll doesn't interpret the markdown comments the way I expected, so it's better to just use HTML comments directly.
----
> docs: fix comments in index.md

- Cargo.lock
- crypto/Cargo.toml
- crypto/src/test_utils/mod.rs
- keystore/Cargo.toml
- keystore/tests/z_entities.rs
pretty_env_logger uses humantime, which is unmaintained (see https://rustsec.org/advisories/RUSTSEC-2025-0014). Also there haven't been updates to pretty_env_logger in 2 years.
> chore: switch from pretty_env_logger to env_logger

- README.md
The adjustments to the docs landing page need to be made prior to pushing to the release commit.
----
> chore: adjust release instructions order

- README.md
There were two lines in the updated instruction, I only shifted the first one of them. This fixes it.
----
> chore: fix release instructions in readme

- Cargo.lock
- Cargo.toml
- README.md
- crypto-ffi/Cargo.toml
- crypto-ffi/bindings/js/src/CoreCrypto.ts
- crypto-ffi/bindings/js/src/CoreCryptoContext.ts
- crypto-ffi/bindings/js/src/CoreCryptoInstance.ts
- crypto-ffi/bindings/js/test/CoreCrypto.test.ts
- crypto-ffi/bindings/js/test/utils.ts
- crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/CoreCrypto.kt
- crypto-ffi/bindings/jvm/src/test/kotlin/com/wire/crypto/MLSTest.kt
- crypto-ffi/src/generic/epoch_observer.rs
- crypto-ffi/src/generic/mod.rs
- crypto-ffi/src/wasm/epoch_observer.rs
- crypto-ffi/src/wasm/mod.rs
- crypto/src/lib.rs
- crypto/src/mls/client/epoch_observer.rs
- crypto/src/mls/client/error.rs
- crypto/src/mls/client/mod.rs
- crypto/src/mls/conversation/conversation_guard/commit.rs
- crypto/src/mls/conversation/conversation_guard/decrypt/buffer_messages.rs
- crypto/src/mls/conversation/conversation_guard/decrypt/mod.rs
- crypto/src/mls/conversation/merge.rs
- crypto/src/mls/conversation/own_commit.rs
- crypto/src/mls/conversation/pending_conversation.rs
- crypto/src/mls/mod.rs
- crypto/src/obfuscate.rs
- crypto/src/test_utils/epoch_observer.rs
- crypto/src/test_utils/mod.rs
- Add an `EpochObserver` API for notifications when the epoch changes
- Deprecate the old `has_epoch_changed` member of the struct returned when decrypting a message
----
> feat: add `EpochObserver` API [WPB-16260]

- docs/index.md
kotlin documentation links on the main page
----
> fix: kotlin documentation links on the main page [WPB-16460]

- crypto-ffi/bindings/uniffi-android/build.gradle.kts
`android-uniffi` library namespace was conflicting the main `android` library
----
> fix: android-uniffi library namespace was conflicting the main android library [WPB-16470]

- .github/workflows/publish-swift.yml
> fix: swift publishing failing due to not running on latest macos runner

- .github/workflows/bindings.yml
- .github/workflows/build-ios.yml
- crypto-ffi/Makefile.toml
- crypto-ffi/bindings/js/package.json
- interop/src/build/web/webdriver.rs
This PR reverts to using our self hosted runners and makes the necessary changes to our workflows to make them compatible.
----
> ci: use chrome-headless-shell instead of chrome --headless [WPB-16565]

- .github/workflows/bindings.yml
- .github/workflows/build-ios.yml
- scripts/clean.sh
We are running low on disk space in our self-hosted runners, also, caches are downloaded as an artifact anyway, so there's no good reason in keeping them.
----
> ci: run cleanup script in macos jobs

- .github/workflows/benchmarks.yml
- .github/workflows/bindings.yml
- .gitignore
- crypto-ffi/Makefile.toml
- crypto-ffi/bindings/js/bun.lock
This PR adds `bun.lock` to the repository and makes sure not to modify it when we run `bun install`, in order to get reproducible builds.
> chore: add bun lockfile [WPB-15718]

- .github/workflows/bindings.yml
- .github/workflows/build-ios.yml
- .github/workflows/publish-jvm.yml
- .github/workflows/publish-swift.yml
- README.md
- crypto-ffi/Makefile.toml
- crypto-ffi/bindings/swift/BuildSettings.xcconfig
- crypto-ffi/bindings/swift/WireCoreCrypto/WireCoreCrypto.xcodeproj/project.pbxproj
- crypto-ffi/bindings/swift/WireCoreCrypto/WireCoreCrypto.xcodeproj/xcshareddata/xcschemes/WireCoreCrypto.xcscheme
- crypto-ffi/bindings/uniffi-jvm/build.gradle.kts
- deny.toml
drop support for darwin x86 targets
----
> build!: drop support for darwin x86_64 targets

- Cargo.lock
- crypto/Cargo.toml
- keystore/Cargo.toml
- mls-provider/Cargo.toml
This reverts commit 7da2234db5144c0484000e9e0e7e009046a5e2b4.
----
> Revert "build(deps): bump rstest from 0.24.0 to 0.25.0"

- .github/actions/setup-and-cache-rust/action.yml
- .github/workflows/benchmarks.yml
- .github/workflows/bindings.yml
- .github/workflows/build-android.yml
- .github/workflows/build-jvm-linux.yml
- .github/workflows/coverage.yml
- .github/workflows/deny.yml
- .github/workflows/docs.yml
- .github/workflows/publish-jvm.yml
- .github/workflows/publish-swift.yml
- .github/workflows/publish-wasm.yml
- .github/workflows/rust.yml
`swatinem/rust-cache` gave us trouble on our runner machine, so we want to use `actions/cache` instead, which is more widely used. To avoid copy and pasting the usage with parameters everywhere, we're it using our own composite action that sets up rust.
----
> ci: move to `actions/cache` from `swatinem/rust-cache`

- interop/src/build/web/wasm.rs
- interop/src/build/web/webdriver.rs
- interop/src/clients/corecrypto/web.rs
- interop/src/clients/cryptobox/web.rs
- interop/src/main.rs
Right now, the interop http server port is always 8000. This means that only one server can run on a single machone. Our CI requires one per user. So we add the current user id to 8000 to avoid port collisions in cases where multiple users run the interop test in parallel.
----
> test: fix constant interop http server test port

- .github/actions/setup-and-cache-rust/action.yml
This solves the problem that builds were cached for only one target on the same runner operating system.
----
> ci: add cache key prefixes

- .github/actions/setup-and-cache-rust/action.yml
- .github/workflows/bindings.yml
The rust target based cache keys don't work in cases where we have multiple targets because cache keys can't contain commas. This adds a custom cache key parameter to our action for the only such case we currently have.
----
> ci: fix cache key prefixes for interop test

- crypto-ffi/src/generic/context/proteus.rs
Re-expose proteus_reload_session which removed by mistake
----
> fix: re-expose proteus_reload_session which removed by mistake [WPB-16700]

- crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/CoreCrypto.kt
- crypto-ffi/bindings/jvm/src/test/kotlin/com/wire/crypto/MLSTest.kt
Don't refer to the internal uniffi EpochObserver type in the public API
----
> fix: don't refer to the internal uniffi EpochObserver type in the public API [WPB-16684]

- Cargo.lock
This resolves RUSTSEC-2025-0022 which fails our CI.
----
> chore: update openssl

- Cargo.lock
This resolves
[RUSTSEC-2025-0023](https://rustsec.org/advisories/RUSTSEC-2025-0023)
----
> build: bump tokio to 1.44.2

- crypto-ffi/bindings/js/src/.gitignore
- crypto-ffi/bindings/js/src/Ciphersuite.ts
- crypto-ffi/bindings/js/src/ConversationConfiguration.ts
- crypto-ffi/bindings/js/src/CoreCrypto.ts
- crypto-ffi/bindings/js/src/CoreCryptoContext.ts
- crypto-ffi/bindings/js/src/CoreCryptoInstance.ts
- crypto-ffi/bindings/js/src/CoreCryptoMLS.ts
Previously clients needed to sometimes use a low-level
`ConversationConfiguration` instance, which required i.e. a `number`
for the ciphersuite instead of an enum variant, with obvious
usability problems resulting.
This creates a high-level `ConversationConfiguration` interface
that they can use instead.
----
> fix: create an inteface for `ConversationConfiguration`

- rust-toolchain.toml
This is to make our builds & CI reproducible in the future. Currently if we go to one of the release branches, we need to hunt for the proper toolchain version in order to pass CI successfully.
> chore: add rust-toolchain.toml

- Cargo.lock
- Cargo.toml
This version includes fixes for tests that were failing due to futures being too big to fit on stack.
> chore: update to latest state wire/stable of our fork of OpenMLS

- Cargo.lock
- crypto/Cargo.toml
- crypto/src/group_store.rs
sysinfo is currently only used to get available RAM on non-wasm platforms, but we really don't need that, and the information is not so useful anyway. On the other hand, sysinfo is another dependency that brings with it a few windows dependencies, which we don't really have a need for.
> chore: drop sysinfo

- Cargo.lock
- extras/webdriver-installation/Cargo.toml
- keystore-dump/Cargo.toml
Also drop the clock feature which we're not really using, which allow us to drop a couple of dependencies.
> chore: update chrono

- crypto/src/mls/conversation/mod.rs
We had a comment in a test asking for parallelization due to a claimed 5m execution time. On investigation, two different team members couldn't get it to take more than 10s. So this just removes the comment.
----
> chore(test): rm comment asking for parallelization [WPB-9624]

- .github/workflows/rust.yml
- crypto/src/e2e_identity/enrollment/test_utils.rs
- crypto/src/ephemeral.rs
- crypto/src/mls/conversation/mod.rs
- crypto/src/proteus.rs
- keystore/src/connection/platform/generic/mod.rs
- keystore/tests/common.rs
The default behavior of our rust action is to fail on warnings.
There is no reason to override that default behavior.
----
> ci(rust.yml): fail on warnings

- crypto/src/mls/conversation/commit.rs
- crypto/src/mls/conversation/commit_delay.rs
- crypto/src/mls/conversation/conversation_guard/decrypt/buffer_messages.rs
- crypto/src/mls/conversation/conversation_guard/decrypt/mod.rs
- crypto/src/mls/conversation/duplicate.rs
- crypto/src/mls/conversation/leaf_node_validation.rs
- crypto/src/mls/conversation/mod.rs
- crypto/src/mls/conversation/orphan_welcome.rs
- crypto/src/mls/conversation/pending_conversation.rs
- crypto/src/mls/conversation/proposal.rs
- crypto/src/mls/conversation/renew.rs
- crypto/src/mls/mod.rs
- crypto/src/mls/session/epoch_observer.rs
- crypto/src/test_utils/context.rs
- crypto/src/test_utils/mod.rs
- crypto/src/test_utils/test_context.rs
- crypto/src/test_utils/test_conversation.rs
- crypto/src/transaction_context/conversation/external_commit.rs
- crypto/src/transaction_context/conversation/external_proposal.rs
- crypto/src/transaction_context/conversation/proposal.rs
- crypto/src/transaction_context/conversation/welcome.rs
- crypto/src/transaction_context/e2e_identity/conversation_state.rs
- crypto/src/transaction_context/e2e_identity/rotate.rs
This PR First, adds necessary features to the test conversaiton before starting to introduce test conversation usage into tests. 
This is the first of two PRs, to avoid piling up too many changes in a single PR.
----
> refactor(test): use test conversation (1/2) [WPB-15788]

- crypto-ffi/bindings/js/src/CoreCryptoContext.ts
- crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/CoreCryptoContext.kt
- crypto-ffi/bindings/jvm/src/test/kotlin/com/wire/crypto/MLSTest.kt
- crypto-ffi/bindings/swift/WireCoreCrypto/WireCoreCryptoTests/WireCoreCryptoTests.swift
- crypto-ffi/src/core_crypto_context/mls.rs
- crypto/src/mls/session/error.rs
- crypto/src/mls/session/mod.rs
- crypto/src/transaction_context/mod.rs
It turns out clients don't actually use this API. And also there is no reason they should use it, since the backend doesn't require presence of a signature key before issuing a client ID.
> refactor!: remove 2-phase MLS init

- crypto-ffi/src/identity/x509.rs
> fix: crypto-ffi: fix field names in X509Identity on wasm

- .github/workflows/rust.yml
- crypto/benches/commit.rs
- crypto/benches/mls_proteus.rs
- crypto/benches/utils/mls.rs
Here targets refer to cargo targets: binaries, tests, benches etc.
> chore: ci: run `cargo check` and clippy for all targets

- .github/workflows/docs.yml
- crypto-ffi/Makefile.toml
- crypto-ffi/src/bindings/mod.rs
- crypto-ffi/src/lib.rs
- docs/FFI.md
- docs/index.md
We're looking for an overall structure like `{tag}/{lang}` for the root of all documentation.
See also https://github.com/wireapp/core-crypto/commit/1dbf96a5379c9396d4724c15d2f125bcb811380e which cleans up the old/irrelevant files from the `gh-pages` branch.
----
> docs: reorganize public docs tree [WPB-17912]

- .github/workflows/unreleased-changes.yml
- docs/index.md
This updates every time we push to `main`, and updates the relevant `UNRELEASED_CHANGES.md` file.
Note that we do _not_ create a stub file in `docs/` because that introduces the risk of accidentally publishing the stub.
----
> docs: publish unreleased changes to github pages

- crypto-ffi/Makefile.toml
The mac specific case was mistakenly removed in 4f4368f04894862f258a8a862240fb4c549b6b86
----
> fix: building android bindings on a mac

- crypto-ffi/bindings/js/test/wdio/database.test.ts
a5e510c2829d6a9e460eb0eff5f213305c93fc51 broke a large test file into many smaller files, and these tests were accidentally omitted.
This re-adds them.
----
> test(js): re-add database tests which were accidentally omitted

- crypto/src/mls/conversation/commit.rs
- crypto/src/mls/conversation/conversation_guard/decrypt/mod.rs
- crypto/src/mls/conversation/conversation_guard/merge.rs
- crypto/src/mls/conversation/own_commit.rs
- crypto/src/mls/conversation/proposal.rs
- crypto/src/mls/conversation/renew.rs
- crypto/src/test_utils/context.rs
- crypto/src/test_utils/test_conversation/commit.rs
- crypto/src/test_utils/test_conversation/mod.rs
- crypto/src/test_utils/test_conversation/proposal.rs
- crypto/src/transaction_context/conversation/external_commit.rs
- crypto/src/transaction_context/conversation/proposal.rs
- crypto/src/transaction_context/e2e_identity/conversation_state.rs
- crypto/src/transaction_context/e2e_identity/rotate.rs
> refactor: test: move API from `SessionContext` to `TestConversation` [WPB-18082]

- .github/workflows/benchmarks.yml
We need to run benches on main, to have a baseline on feature branches
----
> ci: run benchmarks on main

- .pre-commit-config.yaml
To use this, just rerun `pre-commit install --install-hooks`.
With this new section installed, the check for conventional commit messages will actually run.
----
> build: actually install the `conventional-commit` hook

- .pre-commit-config.yaml
Specifically, use the actual set of types which appear in this repo more than once. This is a somewhat broader set than the defaults.
As determined by 
```sh
git log  --oneline | cut -d' ' -f2- | rg '^[^:(!]+' -o | sort | uniq -c | sort -rn | rg -v '^\s*1 '
```
----
> build: add a reasonable set of commit types to legal ones

- crypto-ffi/bindings/jvm/src/test/kotlin/com/wire/crypto/ProteusClientTest.kt
- crypto-ffi/src/error/core_crypto.rs
- crypto-ffi/src/error/mod.rs
- crypto-ffi/src/error/proteus.rs
- crypto/src/error/proteus.rs
Until now, we incorrectly assumed, that we could determine whether a
recursive error is a proteus error by just looking at the innermost
type. However, this approach fails in the case of a
`ConversationNotFoundError`, wrapped in a `LeafError`, which is not
proteus-specific.
Therefore, we're now checking entire error stack for proteus error
kinds.
----
> fix: proteus error type mapping

- .github/workflows/bindings.yml
- crypto-ffi/Makefile.toml
- crypto-ffi/bindings/android/build.gradle.kts
- crypto-ffi/bindings/build.gradle.kts
- crypto-ffi/bindings/gradle.properties
We were already importing dokka 2.0 but we were still using the old v1 gradle tasks. This PR enables the v2 gradle tasks and updates the build config to use them.
----
> chore: upgrade to use Dokka 2.0

- crypto-ffi/bindings/js/src/CoreCryptoError.ts
- crypto-ffi/bindings/js/test/wdio/errors.test.ts
> fix: stop emitting warning on missing error fields [WPB-15468]

- .github/workflows/bindings.yml
- crypto-ffi/bindings/js/benches/CoreCrypto.bench.ts
- crypto-ffi/bindings/js/test/bun/utils.ts
- crypto-ffi/bindings/js/test/wdio/clientIdentity.test.ts
- crypto-ffi/bindings/js/test/wdio/conversation.test.ts
- crypto-ffi/bindings/js/test/wdio/e2ei.test.ts
- crypto-ffi/bindings/js/test/wdio/epochObserver.test.ts
- crypto-ffi/bindings/js/test/wdio/errors.test.ts
- crypto-ffi/bindings/js/test/wdio/externalEntropy.test.ts
- crypto-ffi/bindings/js/test/wdio/historySharing.test.ts
- crypto-ffi/bindings/js/test/wdio/logger.test.ts
- crypto-ffi/bindings/js/test/wdio/proteus.test.ts
- crypto-ffi/bindings/js/test/wdio/setData.test.ts
- crypto-ffi/bindings/js/test/wdio/transactionContext.test.ts
- crypto-ffi/bindings/js/test/wdio/utils.ts
The browser instance is reused, which may lead to conflicts and unexpected behaviour.
> Do not use same IDs across different tests

- .github/dependabot.yml
We've had 4 open dependabot PRs for quite a while, which are essentially blocked on Rust ecosystem moving to rand 0.9. The default dependabot limit for number of opened PRs is 5, which means we only get 1 additional PR, slowing down our updates. So bump the limit to 10.
> chore: ci: bump open PRs limit to 10 for Rust dependencies

- CHANGELOG.md
- crypto-ffi/bindings/swift/WireCoreCrypto/WireCoreCrypto/CoreCrypto.swift
- crypto-ffi/bindings/swift/WireCoreCrypto/WireCoreCrypto/FilePath+Absolute.swift
- crypto-ffi/bindings/swift/WireCoreCrypto/WireCoreCryptoTests/WireCoreCryptoTests.swift
- crypto/src/transaction_context/proteus.rs
Protect against multiple core crypto instances accessing the same key store by holding a file lock on it during a transaction.
----
> feat: protect key store with file lock during transaction

- docs/index.md
Docs weren't built and deployed to the correct directory. We decided that manually building and uploading docs for every platform, which would be necessary to fix this, isn't worth it. Not providing docs for `7.x` will be a good nudge for application developers to migrate to `8.x` as soon as possible.
Also, fix a typo in the rust column.
----
> docs: remove `7.x` series from `index.md`

- crypto-ffi/bindings/swift/WireCoreCrypto/WireCoreCrypto/CoreCrypto.swift
- crypto-ffi/bindings/swift/WireCoreCrypto/WireCoreCryptoTests/WireCoreCryptoTests.swift
The swift compiler gave warnings for classes marked as Sendable and had mutable state. We can resolve the warnings by turning the classes into actors which protect the mutable state.
----
> chore: remove Sendable warnings in the Swift bindings

- .github/workflows/bindings.yml
- .swiftlint.yml
- crypto-ffi/bindings/swift/WireCoreCrypto/WireCoreCrypto/CoreCrypto.swift
- crypto-ffi/bindings/swift/WireCoreCrypto/WireCoreCryptoTests/WireCoreCryptoTests.swift
- interop/src/clients/InteropClient/InteropClient/InteropAction.swift
- interop/src/clients/InteropClient/InteropClient/InteropClientApp.swift
This PR adds Swiftlint to report code quality issues during CI.
Swiftlint configs are added to the swift projects and configured to match settings of swift-format. 
Swiftlint uses --strict to fail on warnings.
A main feature of Swiftlint is the detection of undocumented items and other code guidelines that swift-format does can't check.
----
> ci: use swiftlint for code quality checks [WPB-17421]

- crypto-ffi/bindings/js/src/CoreCrypto.ts
This fixes the following:
error TS2345: Argument of type 'Buffer<ArrayBufferLike>' is not assignable
to parameter of type 'BufferSource'.
> chore: crypto-ffi: fix typedoc warning

- .github/workflows/benchmarks.yml
This is to make it possible to read the full line in github (if it's too long, github will cut it).
> chore: ci: adjust names of benchmark workflow and jobs

- scripts/update-versions.sh
When build the Swift bindings we get the following warning:
```
warning build: Truncating -current_version to fit in 32-bit space used by old mach-o format
```
This is because the `DYLIB_CURRENT_VERSION` is now larger (80000) than 65535, which is the calculated as major * 10000 + minor * 100 + patch.
We shouldn't convert our version into single integer but rather keep it as is since the acceptable format for this version is `xxxx.yy.zz`.
----
> fix: warning about DYLIB_CURRENT_VERSION getting truncated

- Cargo.lock
- crypto-ffi/Cargo.toml
- crypto-ffi/src/error/mod.rs
- keystore-dump/Cargo.toml
- keystore-dump/src/main.rs
It turns out that while `smol` is fine for abstract async execution,
the rust web development community has as a whole chosen `tokio` for
servers. This is relevant because interop runs a tiny little server
for the wasm stuff.
I could not find _any_ approach higher-level than a `TcpStream`
which did not require Tokio, had been updated in the last 3 years,
and had a non-trivial userbase. There are various personal projects,
and there are old projects that generate supply-chain errors, and
then there's Tokio.
As long as interop needs to provide a web server, I think we're
stuck with Tokio.
----
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title …
> build: replace `tokio` with `smol` in direct deps, except interop [WPB-16939]

- Makefile
> build: Makefile: use -f when removing the .stamps directory

- .github/workflows/bindings.yml
- interop/src/clients/InteropClient/delete_simulator.sh
- interop/src/clients/InteropClient/install-interop-client.sh
- scripts/create-ios-sim-device.sh
- scripts/delete-ios-sim-device.sh
With this PR ios tests with device specific xcode build destinations create a dedicated device for test first and remove it after finishing the test. This should avoid any CI errors related to non existent simulator devices when using xcodebuild. 
----
> ci: create xcode simulators when running tests

- .github/workflows/scheduled.yml
This takes 20-ish minutes to run, but it will turn CI red for us if we have broken some tests not covered by a normal run.
Note that this test cannot be demonstrated before merging, as neither `schedule` nor `workflow_dispatch` will do anything until the test is on the default branch, which for us is `main`. 
----
> test: add scheduled test of all features to run nightly on main [WPB-10280]

- .github/actions/make/action.yml
- .github/actions/make/android/lib/action.yml
- .github/actions/make/android/package/action.yml
- .github/actions/make/bindings-kotlin-jvm/action.yml
- .github/actions/make/bindings-swift/action.yml
- .github/actions/make/ffi-library/action.yml
- .github/actions/make/ios/action.yml
- .github/actions/make/jvm-linux/action.yml
- .github/actions/make/uniffi-bindgen/action.yml
- .github/workflows/bindings.yml
- .github/workflows/build-android.yml
- .github/workflows/build-ios.yml
> ci: use GitHub Actions artifacts instead of caches for build artifacts [WPB-17419]

- .github/actions/make/action.yml
This is a workaround for actions/upload-artifact#506 (overwrite behavior is not atomic). The reason why we're getting in this situation is that we want to use the same composite action whenever we want to guarantee that an artifact exists. This makes our workflows more robust in cases where the artifacts that were uploadded by different workflow runs have expired (e.g., a retry several days later).
----
> ci: continue if an uploaded artifact already exists on a run

- Cargo.lock
- deny.toml
- interop/Cargo.toml
- interop/src/clients/corecrypto/ffi.rs
- interop/src/clients/corecrypto/ios.rs
- interop/src/clients/corecrypto/native.rs
- interop/src/clients/corecrypto/web/mod.rs
- interop/src/clients/mod.rs
- interop/src/main.rs
- interop/src/util.rs
- keystore-dump/Cargo.toml
- keystore-dump/src/main.rs
This moves interop and keystore-dump from color-eyre to anyhow. We don't really need color-eyre.
> chore: pacify cargo-deny

- Cargo.lock
backtrace 0.3.71 uses the unmaintained dependency adler. Upgrading to 0.3.75 replaces adler with adler2, which is a maintained clean room alternative implementation
----
> build: bump backtrace from from 0.3.71 to 0.3.75

- .github/workflows/bindings.yml
disables brew auto update during test-ios
----
> ci: disable brew auto update during test-ios

- crypto/Cargo.toml
- crypto/src/obfuscate.rs
Obfuscated values should change "regularly" for some definition of that term. Our goal is to compromise between debugging utility, for which pure determinism is nice, and customer privacy, for which we would simply never reveal any part of any sensitive value.
This solution means that the same value obfuscated on two devices will appear differently in the logs. It also means that the same value obfuscated between restarts of the client will appear differently.
----
> feat: salt obfuscated values

- .github/workflows/publish-android.yml
- .github/workflows/publish-jvm.yml
Publishing may fail at a later time, even when the CI step succeeds, so we're keeping the artifacts on the release.
----
> ci: for Android/JVM, don't delete artifacts after publish step

- .github/actions/make/action.yml
- .github/actions/make/ffi-library/action.yml
- .github/actions/make/jvm/action.yml
- .github/actions/make/set-make-executable/action.yml
- .github/actions/make/uniffi-bindgen/action.yml
- .github/actions/make/web/ts/action.yml
- .github/workflows/build-ios.yml
- .github/workflows/docs-swift.yml
- .github/workflows/package-ios.yml
- .github/workflows/test-ios.yml
login shell was needed so that the runners load bash configs. Instead of relying on hidden configs on our local runners we rather set the make executable in our workflow files.
----
> ci: explicitly set make or gmake [WPB-20142]
