wireapp/core-crypto

crypto/src/client.rs
This fixes loading of a previously-saved client identity in a key store.
=> Use consistent store key for MLS identity

README.md
----
----
Add instructions for how to build & publish CoreCrypto.
----
----
----
=> chore: add instructions for how build & publish

crypto-ffi/Makefile.toml, kotlin/android/build.gradle.kts, kotlin/jvm/build.gradle.kts
----
----
- Add support for linux in the JVM target.
- Build with release flag by default for smaller binaries.
This makes it possible to run tests on cheaper linux VMs.
----
----
----
=> chore: JVM linux support

.gitignore
----
----
Add IntelliJ files/folers to gitignore
----
=> chore: add Intellij files to gitignore

.github/workflows/coverage.yml
----
- [ x is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----
Add test coverage support uploading report to codecov.io
----
=> build: add test coverage support

.github/workflows/audit.yml
----
----
Add security audit support to constantly scan our dependencies for known vulnerabilities
----
=> build: add security auditing

crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt, crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift, crypto-ffi/bindings/swift/include/core_cryptoFFI.h, crypto-ffi/src/CoreCrypto.udl, crypto-ffi/src/lib.rs, crypto/src/client.rs, crypto/src/conversation.rs, crypto/src/error.rs, crypto/src/lib.rs, crypto/src/member.rs
----
----
Cannot leave a conversation easily
Implemented the `leave_conversation` function
----
----
----
=> feat: Added method to leave a conversation [CL-12]

Cargo.toml, cli/Cargo.lock, cli/Cargo.toml, cli/src/main.rs
----
----
Fix cli compilation and include it in workspace for convenience
----
=> chore: fix cli compilation and update it a bit

Cargo.toml, crypto-ffi/Cargo.toml, crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt, crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift, crypto-ffi/bindings/swift/include/core_cryptoFFI.h, crypto-ffi/src/CoreCrypto.udl, crypto-ffi/src/generic.rs, crypto-ffi/src/wasm.rs, crypto/Cargo.toml, crypto/src/client.rs, crypto/src/conversation.rs, crypto/src/credential.rs, crypto/src/error.rs, crypto/src/external_proposal.rs, crypto/src/lib.rs, crypto/src/member.rs, crypto/src/proposal.rs, crypto/src/test_fixture_utils.rs, keystore/Cargo.toml, keystore/benches/read.rs, keystore/benches/write.rs, keystore/src/entities/platform/generic/mls/group.rs, keystore/src/entities/platform/generic/mls/identity.rs, keystore/src/entities/platform/generic/mls/keypackage.rs, keystore/src/error.rs, keystore/src/proteus.rs, keystore/tests/mls.rs
----
----
Adds support for external remove proposals
----
=> feat: external remove proposal support [CL-14]

.gitignore, keystore/Cargo.toml, keystore/src/connection/mod.rs, keystore/src/entities/mod.rs, keystore/src/entities/platform/generic/mls/group.rs, keystore/src/entities/platform/generic/mls/identity.rs, keystore/src/entities/platform/generic/mls/keypackage.rs, keystore/src/entities/platform/generic/proteus/mod.rs, keystore/src/entities/platform/wasm/mls/group.rs, keystore/src/entities/platform/wasm/mls/identity.rs, keystore/src/entities/platform/wasm/mls/keypackage.rs, keystore/src/entities/platform/wasm/proteus/mod.rs, keystore/src/error.rs, keystore/src/lib.rs, keystore/src/mls.rs, keystore/tests/common.rs, keystore/tests/general.rs, keystore/tests/mls.rs, keystore/tests/proteus.rs, keystore/tests/z_entities.rs
----
----
Keystore entities were not sufficiently tested. They also missed implementations that were unused.
Added a test suite for all Keystore entities using all backends
usual test harness
----
=> feat: Added Entity testing to keystore

.github/workflows/rust.yml
----
----
* Abort ci job if `cargo fmt` fails
* Abort ci job if `cargo clippy`
----
=> Add cargo fmt & clippy to CI

.github/workflows/audit.yml, .github/workflows/coverage.yml, .github/workflows/rust.yml
----
----
Tests for LifetimeExtensions were time based, hence they could be flaky when ran on a runner with low resources. This PR:
* Use `--release` profile for all tests to fix time-based tests flakyness
* Applied some of best practices regarding Rust CIs as detailed [here](https://www.reillywood.com/blog/rust-faster-ci/)
* Parallelised a lot of steps de cut rust workflow time by 3
Tests were flaky
----
=> Better, faster CI

crypto-ffi/src/wasm.rs, keystore/Cargo.toml, mls-provider/Cargo.toml, mls-provider/src/crypto_provider.rs
----
----
RustCrypto dependencies are out of date
----
----
=> fix: Updated RustCrypto dependencies to match hpke-rs requirements

crypto-ffi/Cargo.toml, crypto-ffi/bindings/js/CoreCrypto.ts, crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt, crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift, crypto-ffi/bindings/swift/include/core_cryptoFFI.h, crypto-ffi/src/CoreCrypto.udl, crypto-ffi/src/generic.rs, crypto-ffi/src/wasm.rs, crypto/Cargo.toml, crypto/src/conversation/decrypt.rs, crypto/src/conversation/handshake.rs, crypto/src/external_proposal.rs, crypto/src/proposal.rs, crypto/src/test_utils.rs
----
----
After each commit we shall upload GroupInfo for external client to join through an external commit
----
=> expose GroupInfo [CL-60]

crypto-ffi/bindings/js/CoreCrypto.ts, crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt, crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift, crypto-ffi/bindings/swift/include/core_cryptoFFI.h, crypto-ffi/src/CoreCrypto.udl, crypto-ffi/src/generic.rs, crypto-ffi/src/wasm.rs, crypto/src/conversation/handshake.rs, crypto/src/external_commit.rs, crypto/src/test_utils.rs
----
----
rename 'group_info' into 'public_group_state'
----
=> rename 'group_info' into 'public_group_state'

CHANGELOG.md, CHANGELOG.tpl, Cargo.toml, crypto-ffi/Cargo.toml, crypto/Cargo.toml, keystore/Cargo.toml, mls-provider/Cargo.toml
Pinned deps to prevent further breakage
=> chore: Release v0.3.1

Cargo.toml, crypto-ffi/bindings/js/CoreCrypto.ts, crypto-ffi/bindings/js/test/CoreCrypto.test.js, crypto-ffi/src/CoreCrypto.udl, crypto-ffi/src/generic.rs, crypto-ffi/src/wasm.rs, crypto/Cargo.toml, crypto/src/conversation/decrypt.rs, crypto/src/conversation/handshake.rs, crypto/src/conversation/merge.rs, crypto/src/conversation/renew.rs, crypto/src/error.rs, crypto/src/lib.rs, crypto/src/proposal.rs
----
----
* expose `clear_pending_commit` to rollback a local pending commit not fanned out to other clients
* expose `clear_pending_proposal` to rollback a local pending proposal not fanned out to other clients
* all methods creating a proposal now return a reference which can be used to clear that proposal
----
=> Clear pending commit/proposal [CL-57]

crypto-ffi/bindings/js/CoreCrypto.ts, crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt, crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift, crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift, crypto-ffi/bindings/swift/lib/core_cryptoFFI.h, crypto-ffi/src/CoreCrypto.udl, crypto-ffi/src/generic.rs, crypto-ffi/src/wasm.rs, crypto/src/conversation/handshake.rs, crypto/src/conversation/mod.rs, crypto/src/conversation/public_group_state.rs, crypto/src/conversation/renew.rs, crypto/src/error.rs, crypto/src/test_utils.rs
----
----
All operations returning commits now return a byte array with the commit bundle serialized instead of a struct.
`PublicGroupState` has also been bundled to prepare it for future evolutions.
----
=> returnTLS serialized CommitBundle [CL-79]

CHANGELOG.md, CHANGELOG.tpl, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto/Cargo.toml, keystore/Cargo.toml, mls-provider/Cargo.toml, package.json
----
----
Release new version
----
=> Release v0.4.0

crypto-ffi/Cargo.toml, crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt, crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift, crypto-ffi/bindings/swift/lib/core_cryptoFFI.h, crypto-ffi/src/CoreCrypto.udl
----
----
* uniffi breaking changes in patch release
* ffi error due to unused `TlsMemberAddedMessages`
----
=> fix uniffi breaking changes

Cargo.toml
=> fix: rollback openmls & chrono in order to release 0.5.0

CHANGELOG.md, CHANGELOG.tpl, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto-ffi/bindings/js/CoreCrypto.ts, crypto-ffi/bindings/js/test/CoreCrypto.test.js, crypto/Cargo.toml, interop/Cargo.toml, keystore/Cargo.toml, mls-provider/Cargo.toml, package.json
=> chore: release v0.5.1 [CL-87]

CHANGELOG.md, CHANGELOG.tpl, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto/Cargo.toml, interop/Cargo.toml, keystore/Cargo.toml, mls-provider/Cargo.toml, package.json
=> chore: Release v0.5.2

.github/workflows/deny.yml, .github/workflows/rust.yml, deny.toml, interop/Cargo.toml
----
----
Add a job for executing [cargo-deny](https://github.com/EmbarkStudios/cargo-deny) and verifying vulnerabilities, code sources, licenses etc..
Also speed up the CI a bit (got slow lately) by parallelizing jobs
----
=> build: add cargo deny job

README.md, crypto-ffi/Makefile.toml
----
----
Add M1 support for the JVM bindings.
----
----
----
=> chore: add m1 support for the jvm bindings

crypto-ffi/bindings/js/CoreCrypto.ts, crypto-ffi/bindings/js/test/CoreCrypto.test.js, crypto-ffi/src/CoreCrypto.udl, crypto-ffi/src/wasm.rs, crypto/src/external_proposal.rs, crypto/src/lib.rs, crypto/src/test_utils.rs
----
----
Callback name was still misleading
----
=> feat!: rename callback client_id_belongs_to_one_of

crypto-ffi/src/generic.rs, crypto-ffi/src/wasm.rs, crypto/src/conversation/mod.rs, crypto/src/external_proposal.rs
----
----
Ensure `external_senders` do not need to be passed explicitly
----
=> test: infer external-senders

crypto-ffi/bindings/js/CoreCrypto.ts, crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt, crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift, crypto-ffi/bindings/swift/lib/core_cryptoFFI.h, crypto-ffi/src/CoreCrypto.udl, crypto-ffi/src/wasm.rs, crypto/src/conversation/decrypt.rs, crypto/src/conversation/handshake.rs, crypto/src/error.rs, crypto/src/external_commit.rs, crypto/src/external_proposal.rs, crypto/src/lib.rs, crypto/src/test_utils.rs
----
----
Adds a verification step in CC for external commits as well (in addition to the verification in place in wire-server). We verify here that:
* sender client_id belongs to a user who is already in the MLS group
* sender user has the right role == is allowed to join by external commit
----
=> feat: validate received external commits

interop/Cargo.toml, interop/src/main.rs
----
----
fix compilation errors when building the project for wasm on macos. 'interop' crate failed compiling because of 'sys' crate
----
=> build: fix compilation errors when building the project for wasm on macos

.github/workflows/rust.yml
----
----
add 'cargo-hack' CI step to ensure all declared features used in isolation, do not break compilation.
Fix raised issues after #125 gets merged
----
=> build: ensure all declared features used in isolation do not break compilation

crypto-ffi/bindings/js/CoreCrypto.ts, crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt, crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift, crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift, crypto-ffi/bindings/swift/lib/core_cryptoFFI.h, crypto-ffi/src/CoreCrypto.udl, crypto-ffi/src/generic.rs, crypto-ffi/src/wasm.rs, crypto/src/mls/conversation/decrypt.rs
----
----
Returns a flag indicating if the decrypted message changed the epoch or not.
----
=> feat: Returning if decrypted message changed the epoch - CL-92

crypto-ffi/Cargo.toml
=> build: bump uniffi 0.21

CHANGELOG.md, CHANGELOG.tpl, Cargo.toml, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt, crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift, crypto-ffi/bindings/swift/lib/core_cryptoFFI.h, crypto/Cargo.toml, interop/Cargo.toml, keystore/Cargo.toml, mls-provider/Cargo.toml, package.json
----
----
New pre-release. Check CHANGELOG
----
=> Pre-Release v0.6.0

CHANGELOG.md, CHANGELOG.tpl, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto/Cargo.toml, crypto/src/lib.rs, crypto/src/proteus.rs, interop/Cargo.toml, keystore/Cargo.toml, keystore/benches/read.rs, keystore/benches/write.rs, mls-provider/Cargo.toml, package.json
----
----
New pre-release. Check CHANGELOG
----
=> Pre-Release v0.6.0 + proteus support

.editorconfig, .github/workflows/audit.yml, .github/workflows/coverage.yml, .github/workflows/docs.yml, .github/workflows/publish-android.yml, .github/workflows/publish-jvm.yml, .github/workflows/publish-wasm.yml, .github/workflows/rust.yml, CHANGELOG.tpl, README.md, kotlin/android/build.gradle.kts, kotlin/build.gradle.kts, kotlin/jvm/build.gradle.kts
----
----
Adds a step in the CI to publish JVM and Android packages.
----
=> chore: Add action to publish jvm/android packages and move to maintained rust toolchain

CHANGELOG.md, CHANGELOG.tpl, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto/Cargo.toml, interop/Cargo.toml, keystore/Cargo.toml, kotlin/android/build.gradle.kts, kotlin/jvm/build.gradle.kts, mls-provider/Cargo.toml, package.json
=> Release 0.6.0-pre.3

.github/workflows/publish-swift.yml
=> fix: Publication of swift packages [CL-49]

crypto-ffi/bindings/js/CoreCrypto.ts, crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt, crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift, crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift, crypto-ffi/bindings/swift/lib/core_cryptoFFI.h, crypto-ffi/src/CoreCrypto.udl, crypto-ffi/src/generic.rs, crypto-ffi/src/wasm.rs, crypto/src/lib.rs, crypto/src/proteus.rs
----
----
Expose function to check if proteus session exists
----
=> feat: Expose session exists through the ffi - CL-101

crypto/src/mls/client.rs, keystore/src/connection/mod.rs, keystore/src/connection/platform/generic/mod.rs, keystore/src/error.rs, keystore/tests/mls.rs, keystore/tests/proteus.rs
----
----
Handle new clippy lints appearing in Rust 1.65
----
=> chore: fix new clippy warnings in 1.65

Cargo.toml, crypto/src/mls/conversation/mod.rs, crypto/src/test_utils/fixtures.rs
----
----
ensure everything keeps working when pure ciphertext format policy is selected. This only affects external proposals/commits which were not compatible. All the heavy lifting is in openmls
----
=> test: pure ciphertext

CHANGELOG.md, CHANGELOG.tpl, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto/Cargo.toml, interop/Cargo.toml, keystore/Cargo.toml, kotlin/android/build.gradle.kts, kotlin/jvm/build.gradle.kts, mls-provider/Cargo.toml, package.json
----
----
New pre-release
----
=> Release 0.6.0-pre.4

CHANGELOG.md, CHANGELOG.tpl, README.md, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto/Cargo.toml, interop/Cargo.toml, keystore/Cargo.toml, kotlin/android/build.gradle.kts, kotlin/jvm/build.gradle.kts, mls-provider/Cargo.toml, package.json
=> Release v0.6.0-pre.5

crypto-ffi/bindings/js/CoreCrypto.ts, crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt, crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift, crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift, crypto-ffi/bindings/swift/lib/core_cryptoFFI.h, crypto-ffi/src/CoreCrypto.udl, crypto-ffi/src/generic.rs, crypto-ffi/src/wasm.rs, crypto/src/proteus.rs
----
----
Exposes function to return fingerprint from prekey bundle from proteus.
----
=> feat: Expose proteus prekey fingerprint - CL-107

crypto/src/mls/conversation/handshake.rs
----
----
Ensure we are immune to duplicate commits and out of order commit/proposal
----
=> test: ensure commit/proposal delivery semantics

crypto/Cargo.toml, crypto/benches/commit.rs, crypto/benches/create_group.rs, crypto/benches/encryption.rs, crypto/benches/key_package.rs, crypto/benches/mls_proteus.rs, crypto/benches/proposal.rs, crypto/benches/public_group_state.rs, crypto/benches/scripts/run.sh, crypto/benches/scripts/test.sh, crypto/benches/utils/mls.rs, crypto/benches/utils/mod.rs, crypto/benches/utils/proteus_bench.rs
----
----
Add ciphersuites 2, 3 & 7  
Compare MLS to Proteus
----
=> bench: more ciphersuites and compare MLS to Proteus

interop/Cargo.toml
=> build: fix sha-1 crate related compilation issue

CHANGELOG.tpl, xtask/Cargo.lock, xtask/Cargo.toml, xtask/src/documentation/changelog.rs, xtask/src/release/bump.rs
=> chore: xtask improvements

crypto/Cargo.toml, crypto/src/proteus.rs, interop/Cargo.toml, interop/src/clients/cryptobox/web.rs, keystore/Cargo.toml, keystore/src/connection/mod.rs
Closes #210 
Closes #208 
Closes #207
=> chore: Updated base64, lru and spinoff deps

crypto-ffi/bindings/js/CoreCrypto.ts, crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt, crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift, crypto-ffi/bindings/swift/lib/core_cryptoFFI.h, crypto-ffi/src/CoreCrypto.udl, crypto-ffi/src/generic.rs, crypto-ffi/src/wasm.rs, crypto/src/e2e_identity/mod.rs, crypto/src/e2e_identity/types.rs, crypto/src/lib.rs, interop/src/clients/corecrypto/e2ei.js, interop/src/clients/corecrypto/web.rs
----
----
With the Typescript bindings
----
=> feat: expose end to end identity web API [CL-21] (part 2)

CHANGELOG.md, CHANGELOG.tpl, README.md, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto/Cargo.toml, interop/Cargo.toml, keystore/Cargo.toml, kotlin/android/build.gradle.kts, kotlin/jvm/build.gradle.kts, mls-provider/Cargo.toml, package.json
----
----
0.6.0-rc.4 release
----
=> chore: 0.6.0-rc.4 release

.github/workflows/bindings.yml, Cargo.toml, crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt, crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift, crypto-ffi/bindings/swift/lib/core_cryptoFFI.h, crypto-ffi/src/CoreCrypto.udl, crypto-ffi/src/generic.rs, crypto-ffi/src/lib.rs, crypto-ffi/src/wasm.rs, crypto/Cargo.toml, crypto/src/error.rs, crypto/src/mls/mod.rs, crypto/src/test_utils/proteus_utils.rs, interop/Cargo.toml, interop/src/main.rs, keystore/.cargo/config.toml, keystore/Cargo.toml, keystore/src/error.rs
Most of the work is in https://github.com/wireapp/proteus/tree/otak/2.0-error-codes
In particular in https://github.com/wireapp/proteus/blob/otak/2.0-error-codes/crates/proteus-traits/src/lib.rs#L27-L70
which lists all the error codes. 
I also added in the proteus code inline comments to highlight when we trigger error codes in certain situations such as here: https://github.com/wireapp/proteus/blob/otak/2.0-error-codes/src/internal/session.rs#L266
=> feat: Proteus errors

.github/workflows/coverage.yml
=> chore: Moved codecov from tarpaulin to llvm-cov

crypto/Cargo.toml, crypto/src/test_utils/fixtures.rs, interop/Cargo.toml, interop/src/util.rs, keystore/Cargo.toml, mls-provider/Cargo.toml
=> chore(deps): Update deps

crypto-ffi/bindings/js/CoreCrypto.ts, crypto-ffi/bindings/js/test/CoreCrypto.test.js, crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt, crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift, crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift, crypto-ffi/bindings/swift/lib/core_cryptoFFI.h, crypto-ffi/src/CoreCrypto.udl, crypto-ffi/src/generic.rs, crypto-ffi/src/wasm.rs, crypto/Cargo.toml, crypto/src/error.rs, crypto/src/mls/client.rs, crypto/src/mls/mod.rs
=> feat: Externally-generated clients [CL-130]

CHANGELOG.md, CHANGELOG.tpl, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto-ffi/bindings/js/test/CoreCrypto.test.js, crypto/Cargo.toml, interop/Cargo.toml, keystore/Cargo.toml, kotlin/android/build.gradle.kts, kotlin/jvm/build.gradle.kts, mls-provider/Cargo.toml, package.json
----
----
Release 0.6.1
----
----
----
=> chore: Release 0.6.1

kotlin/jvm/build.gradle.kts
----
----
JVM CoreCrypto fails at runtime
Native libraries aren't found
Move native libraries to the package root.
----
----
----
=> chore: fix native libraries not loading by moving them to the package root

.github/workflows/publish-jvm.yml
----
----
Kalium CI tests crashes at runtime
CoreCrypto requires a newer version of libc than what the CI environment provides.
Build linux target on Ubuntu LTS (22.04)
----
----
----
=> chore: build linux artifacts on Ubuntu LTS for better compatibility

CHANGELOG.md, CHANGELOG.tpl, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto/Cargo.toml, interop/Cargo.toml, keystore/Cargo.toml, kotlin/android/build.gradle.kts, kotlin/jvm/build.gradle.kts, mls-provider/Cargo.toml, package.json
----
----
Release 0.6.3
----
----
----
=> chore: Release 0.6.3

Cargo.toml, crypto-ffi/Cargo.toml, mls-provider/Cargo.toml, mls-provider/src/crypto_provider.rs
Closes #268 
Closes #267 
Closes #266
=> chore: Updated deps

xtask/Cargo.lock, xtask/Cargo.toml
Fixes https://github.com/wireapp/core-crypto/security/dependabot/14
=> fix(security): Fix rustsec advisories on xtask deps

Cargo.toml, crypto-ffi/bindings/js/CoreCrypto.ts, crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt, crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift, crypto-ffi/bindings/swift/lib/core_cryptoFFI.h, crypto-ffi/src/CoreCrypto.udl, crypto-ffi/src/generic.rs, crypto-ffi/src/wasm.rs, crypto/src/e2e_identity/error.rs, crypto/src/e2e_identity/mod.rs, interop/src/clients/corecrypto/e2ei.js
----
----
Update e2e identity API after [this PR](https://github.com/wireapp/rusty-jwt-tools/pull/47)
----
=> feat!: end-to-end identity API update

crypto-ffi/Cargo.toml, crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt, crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift, crypto-ffi/bindings/swift/lib/core_cryptoFFI.h
=> build: uniffi 0.23

Cargo.toml, crypto/Cargo.toml, crypto/src/mls/credential.rs, crypto/src/test_utils/fixtures.rs
=> chore: some nits before 0.7.0-rc.5

keystore/Cargo.toml, keystore/src/connection/platform/generic/mod.rs
=> fix: Fixed iOS keychain handling with proper attributes [CL-157]

CHANGELOG.md, CHANGELOG.tpl, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto/Cargo.toml, interop/Cargo.toml, keystore/Cargo.toml, kotlin/android/build.gradle.kts, kotlin/jvm/build.gradle.kts, mls-provider/Cargo.toml, package.json
=> build: release 0.8.1

crypto-ffi/bindings/kt/main/com/wire/crypto/CoreCrypto.kt, crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift, crypto-ffi/bindings/swift/lib/core_cryptoFFI.h
----
----
The generated bindings are out of date.
Update bindings.
----
----
----
=> chore: update bindings

.github/workflows/rust.yml, crypto-ffi/src/wasm.rs, crypto/src/group_store.rs, keystore/benches/read.rs, keystore/benches/write.rs, keystore/src/connection/platform/wasm/mod.rs, keystore/src/entities/platform/wasm/mls/group.rs
----
----
Add a CI check for WASM and fix the current lints
----
=> chore: clippy for wasm

crypto-ffi/Cargo.toml, interop/Cargo.toml, interop/src/clients/corecrypto/e2ei.js, interop/src/clients/corecrypto/ffi.rs, interop/src/clients/corecrypto/mod.rs, interop/src/clients/corecrypto/web.rs, interop/src/clients/mod.rs, interop/src/main.rs
----
----
In order to have a even higher confidence over the FFI we deliver, have the interop runner test the generic FFI natively.
----
=> test: have interop runner verify the generic FFI

crypto-ffi/src/generic.rs, crypto/src/proteus.rs
----
----
When `restore_from_disk` is called, it will restore proteus sessions too if the feature flag is enabled.
----
=> fix: Reload proteus sessions when `restore_from_disk` is called - CL-168

CHANGELOG.md, CHANGELOG.tpl, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto/Cargo.toml, interop/Cargo.toml, keystore/Cargo.toml, kotlin/android/build.gradle.kts, kotlin/jvm/build.gradle.kts, mls-provider/Cargo.toml, package.json
=> build: release 0.9.0

CHANGELOG.md, CHANGELOG.tpl, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto/Cargo.toml, interop/Cargo.toml, keystore/Cargo.toml, keystore/src/connection/platform/generic/migrations/V1__schema.sql, keystore/src/connection/platform/generic/migrations/V4__e2ei.sql, kotlin/android/build.gradle.kts, kotlin/jvm/build.gradle.kts, mls-provider/Cargo.toml, package.json
Contains a fix for database migrations
=> chore: Release v0.9.2

crypto-ffi/bindings/kt/main/com/wire/crypto/client/CoreCryptoCentral.kt, crypto-ffi/bindings/kt/main/com/wire/crypto/client/E2eiClient.kt, crypto-ffi/bindings/kt/main/com/wire/crypto/client/MLSClient.kt, crypto-ffi/bindings/kt/test/com/wire/crypto/client/MLSClientTest.kt, crypto-ffi/src/generic.rs, crypto/Cargo.toml
----
----
mobile FFI was failing when initializing MLS client due to a Arc being incremented one too many times. Also add the E2EI API in the Kotlin wrapper and a test for it
----
=> fix: E2EI mobile FFI

CHANGELOG.md, CHANGELOG.tpl, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto/Cargo.toml, interop/Cargo.toml, keystore/Cargo.toml, kotlin/android/build.gradle.kts, kotlin/jvm/build.gradle.kts, mls-provider/Cargo.toml, package.json
=> build: release 0.10.0

CHANGELOG.md, CHANGELOG.tpl, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto/Cargo.toml, interop/Cargo.toml, keystore/Cargo.toml, kotlin/android/build.gradle.kts, kotlin/jvm/build.gradle.kts, mls-provider/Cargo.toml, package.json
=> build: release 0.11.0

crypto-ffi/bindings/js/test/CoreCrypto.test.js, crypto-ffi/src/generic.rs, crypto-ffi/src/wasm.rs, crypto/benches/create_group.rs, crypto/src/mls/conversation/decrypt.rs, crypto/src/mls/conversation/group_info.rs, crypto/src/mls/conversation/handshake.rs, crypto/src/mls/conversation/renew.rs, crypto/src/mls/external_commit.rs, crypto/src/test_utils/central.rs, crypto/src/test_utils/message.rs
----
----
backend sends raw GroupInfo, we were trying to deserialize it from a MlsMessage
----
=> fix: [draft-20] GroupInfo

CHANGELOG.md, CHANGELOG.tpl, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto/Cargo.toml, interop/Cargo.toml, keystore/Cargo.toml, kotlin/android/build.gradle.kts, kotlin/jvm/build.gradle.kts, mls-provider/Cargo.toml, package.json
=> build: release 1.0.0-pre.6

.github/workflows/publish-swift.yml
----
----
IOS client is upgrading to Xcode 14.3.1 so we should do it as well.
----
----
----
=> chore: build swift bindings with xcode 14.3.1

crypto-ffi/bindings/js/CoreCrypto.ts, crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift, crypto-ffi/src/CoreCrypto.udl, crypto/src/error.rs, crypto/src/mls/conversation/mod.rs, crypto/src/mls/conversation/orphan_welcome.rs, crypto/src/mls/conversation/welcome.rs, crypto/src/mls/credential/trust_anchor.rs
----
----
Handle the case when a client tries to decrypt a Welcome referring to a KeyPackage he already has deleted locally
----
=> feat!: orphan Welcome [WPB-3501]

crypto-ffi/bindings/js/CoreCrypto.ts
=> fix: `e2eiRotateAll` return type was not wrapped

CHANGELOG.md, CHANGELOG.tpl, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto/Cargo.toml, interop/Cargo.toml, keystore-dump/Cargo.toml, keystore/Cargo.toml, kotlin/gradle.properties, mls-provider/Cargo.toml, package.json
=> chore: release 1.0.0-rc.6

.github/workflows/rust.yml, crypto-ffi/bindings/js/test/wasm-tests.sh
=> test: fix wasm test hitting a limit. Just split them for now, waiting for a proper solution

crypto-ffi/bindings/js/CoreCrypto.ts, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/E2eiClient.kt, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/MLSClient.kt, crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift, crypto-ffi/src/generic.rs, crypto-ffi/src/wasm.rs, crypto/src/e2e_identity/identity.rs, crypto/src/mls/buffer_external_commit.rs, crypto/src/mls/client/identifier.rs, crypto/src/mls/conversation/buffer_messages.rs, crypto/src/mls/conversation/commit_delay.rs, crypto/src/mls/credential/ext.rs, crypto/src/mls/credential/mod.rs, crypto/src/mls/credential/trust_anchor.rs, crypto/src/proteus.rs, crypto/src/test_utils/central.rs, extras/wasm-browser-run/src/lib.rs, keystore/src/connection/mod.rs, keystore/src/entities/platform/wasm/mls/credential.rs, keystore/src/entities/platform/wasm/mls/signature_keypair.rs
=> fix: TLS serialization of x509 credential

crypto/src/e2e_identity/stash.rs
=> fix: change e2ei enrollment identifier causing collisions

Cargo.toml, crypto-ffi/bindings/js/CoreCrypto.ts, crypto-ffi/bindings/js/test/CoreCrypto.test.js, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/E2eiClient.kt, crypto-ffi/bindings/jvm/src/test/kotlin/com/wire/crypto/client/E2EITest.kt, crypto-ffi/src/generic.rs, crypto-ffi/src/wasm.rs, crypto/Cargo.toml, crypto/src/e2e_identity/identity.rs, crypto/src/e2e_identity/mod.rs, crypto/src/e2e_identity/rotate.rs, crypto/src/e2e_identity/types.rs, crypto/src/mls/conversation/self_commit.rs
=> feat!: bump rusty-jwt-tools to v0.5.0

crypto-ffi/bindings/js/CoreCrypto.ts, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/ByteUtils.kt, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/MlsModel.kt, crypto-ffi/src/generic.rs, crypto-ffi/src/wasm.rs, crypto/src/e2e_identity/identity.rs, crypto/src/mls/credential/ext.rs, crypto/src/test_utils/central.rs
=> feat!: return raw PEM certificate in `getUserIdentities`

crypto-ffi/bindings/js/CoreCrypto.ts, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/CoreCryptoCentral.kt, crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift, crypto/Cargo.toml, crypto/src/e2e_identity/mod.rs
----
- [] contains a reference JIRA issue number like `SQPIT-764`
----
=> feat: add e2ei ffi in Swift wrapper

CHANGELOG.md, CHANGELOG.tpl, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto-ffi/bindings/gradle.properties, crypto/Cargo.toml, interop/Cargo.toml, keystore-dump/Cargo.toml, keystore/Cargo.toml, mls-provider/Cargo.toml, package.json
=> chore: release 1.0.0-rc.13

.cargo/config.toml, CHANGELOG.md, CHANGELOG.tpl, Cargo.toml, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto-ffi/bindings/gradle.properties, crypto-ffi/bindings/js/CoreCrypto.ts, crypto/Cargo.toml, crypto/src/mls/credential/mod.rs, crypto/src/mls/member.rs, interop/Cargo.toml, keystore-dump/Cargo.toml, keystore/Cargo.toml, mls-provider/Cargo.toml, package.json
----
- [] contains a reference JIRA issue number like `SQPIT-764`
----
+ some minors fixes
----
=> build: release v1.0.0 rc.15

.github/workflows/rust.yml, Cargo.toml, extras/keystore-regression-versions/Cargo.toml, extras/keystore-regression-versions/cc-keystore-08/Cargo.toml, extras/keystore-regression-versions/cc-keystore-08/src/main.rs, extras/keystore-regression-versions/cc-keystore-10p/Cargo.toml, extras/keystore-regression-versions/cc-keystore-10p/src/main.rs, extras/keystore-regression-versions/cc-keystore-10r/Cargo.toml, extras/keystore-regression-versions/cc-keystore-10r/src/main.rs, extras/keystore-regression-versions/cc-keystore-current/Cargo.toml, extras/keystore-regression-versions/cc-keystore-current/src/main.rs, extras/keystore-regression-versions/cc-keystore-support/Cargo.toml, extras/keystore-regression-versions/cc-keystore-support/src/lib.rs, extras/keystore-regression-versions/src/main.rs
=> Keystore schema migration regression test

extras/keystore-regression-versions/cc-keystore-09/Cargo.toml, extras/keystore-regression-versions/cc-keystore-09/src/main.rs, extras/keystore-regression-versions/src/main.rs
----
----
Testing for iOS
----
=> test: test DB migration from 0.9.2

CHANGELOG.md, CHANGELOG.tpl, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto-ffi/bindings/gradle.properties, crypto/Cargo.toml, interop/Cargo.toml, keystore-dump/Cargo.toml, keystore/Cargo.toml, mls-provider/Cargo.toml, package.json
=> release: v1.0.0-rc.21

crypto/src/e2e_identity/identity.rs, crypto/src/e2e_identity/mod.rs
=> test: verify that clients can create conversation with x509 credentials

README.md
----
----
The `create-swift-package` task doesn't exist anymore
Use `ios-create-xcframework` instead.
----
----
----
=> fix: README mentions a task which doesn't exist

crypto-ffi/bindings/js/CoreCrypto.ts, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/CoreCryptoCentral.kt, crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift, crypto-ffi/src/generic.rs, crypto-ffi/src/wasm.rs, crypto/src/e2e_identity/rotate.rs
=> feat(e2ei)!: remove 'clientId' from activation & rotate enrollment

crypto-ffi/bindings/android/build.gradle.kts, crypto-ffi/bindings/jvm/build.gradle.kts
----
----
JVM dependencies were enforced by CoreCrypto
Use 'implementation' Gradle configuration instead of 'api'
----
=> fix: use 'implementation' Gradle configuration [WPB-4443]

CHANGELOG.md, CHANGELOG.tpl, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto-ffi/bindings/gradle.properties, crypto/Cargo.toml, crypto/src/group_store.rs, interop/Cargo.toml, keystore-dump/Cargo.toml, keystore/Cargo.toml, mls-provider/Cargo.toml, package.json, xtask/Cargo.lock, xtask/Cargo.toml, xtask/src/release/bump.rs
=> Release v1.0.0-rc.32

crypto/src/test_utils/mod.rs, crypto/src/test_utils/x509.rs, keystore/src/entities/platform/generic/mls/e2ei_crl.rs, keystore/src/entities/platform/generic/mls/e2ei_intermediate_cert.rs, keystore/src/entities/platform/wasm/mls/e2ei_crl.rs, keystore/src/entities/platform/wasm/mls/e2ei_intermediate_cert.rs, keystore/tests/z_entities.rs
=> Fix: intermediate & crl uniqueness constraint

crypto/src/e2e_identity/init_certificates.rs, crypto/src/e2e_identity/mod.rs
=> feat(e2ei): filter out root CA when registering intermediates in case the provider repeats it

Cargo.toml, crypto-ffi/bindings/js/CoreCrypto.ts, crypto-ffi/bindings/js/test/CoreCrypto.test.js, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/E2EIModel.kt, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/MLSClient.kt, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/MlsModel.kt, crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift, crypto-ffi/src/generic.rs, crypto-ffi/src/wasm.rs, crypto/src/e2e_identity/rotate.rs, crypto/src/lib.rs, crypto/src/mls/conversation/commit.rs, crypto/src/mls/conversation/commit_delay.rs, crypto/src/mls/conversation/decrypt.rs, crypto/src/mls/conversation/mod.rs, crypto/src/mls/conversation/proposal.rs, crypto/src/mls/conversation/renew.rs, crypto/src/mls/conversation/welcome.rs, crypto/src/mls/credential/crl.rs, crypto/src/mls/credential/mod.rs, crypto/src/mls/external_commit.rs, crypto/src/mls/external_proposal.rs, crypto/src/mls/proposal.rs, interop/src/clients/corecrypto/ffi.rs, interop/src/clients/corecrypto/native.rs, interop/src/clients/corecrypto/web.rs
=> feat!: add CRL Distribution Point in relevant methods

crypto-ffi/bindings/js/CoreCrypto.ts, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/CoreCryptoCentral.kt, crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift, crypto-ffi/src/generic.rs, crypto-ffi/src/wasm.rs, crypto/src/e2e_identity/init_certificates.rs
=> feat(e2ei)!: return CRL Distribution Points when registering intermediate certificates

crypto-ffi/src/generic.rs, crypto-ffi/src/wasm.rs, crypto/src/e2e_identity/conversation_state.rs, crypto/src/e2e_identity/rotate.rs, crypto/src/mls/conversation/commit.rs, crypto/src/mls/conversation/leaf_node_validation.rs, crypto/src/mls/credential/mod.rs, crypto/src/mls/external_commit.rs, crypto/src/mls/external_proposal.rs, crypto/src/test_utils/central.rs, mls-provider/Cargo.toml
=> fix: verify group info

crypto/src/error.rs, crypto/src/mls/conversation/commit.rs, crypto/src/mls/conversation/decrypt.rs, crypto/src/mls/conversation/duplicate.rs, crypto/src/mls/conversation/proposal.rs, crypto/src/mls/external_commit.rs
=> fix!: Add dedicated error for stale commits and proposals [WPB-6436]

CHANGELOG.md, CHANGELOG.tpl, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto-ffi/bindings/gradle.properties, crypto/Cargo.toml, interop/Cargo.toml, keystore-dump/Cargo.toml, keystore/Cargo.toml, mls-provider/Cargo.toml, package.json, xtask/Cargo.lock, xtask/Cargo.toml
=> build: Release v1.0.0-rc.37

crypto/src/e2e_identity/mod.rs, crypto/src/mls/credential/crl.rs, crypto/src/mls/credential/mod.rs, crypto/src/test_utils/x509.rs
=> Fix: e2ei register intermediate

CHANGELOG.md, CHANGELOG.tpl, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto-ffi/bindings/gradle.properties, crypto/Cargo.toml, interop/Cargo.toml, keystore-dump/Cargo.toml, keystore/Cargo.toml, mls-provider/Cargo.toml, package.json
=> release: v1.0.0-rc.38

Cargo.toml, crypto/Cargo.toml, crypto/src/e2e_identity/mod.rs, mls-provider/Cargo.toml
=> feat: add display name in dpop token

crypto/src/e2e_identity/init_certificates.rs, crypto/src/test_utils/x509.rs
=> fix: Harden x509 validation & revocation checks

crypto-ffi/bindings/js/CoreCrypto.ts, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/MlsModel.kt, crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift, crypto-ffi/src/generic.rs, crypto-ffi/src/wasm.rs, crypto/src/e2e_identity/device_status.rs, crypto/src/e2e_identity/identity.rs
=> feat: add serialNumber, notBefore & notAfter in `WireIdentity` object

crypto-ffi/bindings/js/CoreCrypto.ts
=> fix: TS mapping of identities was using experimental methods

keystore/src/connection/platform/wasm/mod.rs
=> fix: Integrate -pre version to iDB store version

crypto/src/e2e_identity/conversation_state.rs, crypto/src/mls/client/key_package.rs, crypto/src/mls/conversation/leaf_node_validation.rs
=> fix: KeyPackage lifetime validation when receiving messages

crypto/src/e2e_identity/rotate.rs, crypto/src/mls/client/mod.rs
=> fix: Remove cached is_e2ei_capable flag

extras/wasm-browser-run/Cargo.toml, extras/wasm-browser-run/src/webdriver.rs
=> fix: Prevent double-creating WASM stores

.cargo/audit.toml, crypto-ffi/bindings/js/test/CoreCrypto.test.js, deny.toml, extras/keystore-regression-versions/Cargo.toml, extras/keystore-regression-versions/cc-keystore-08/Cargo.toml, extras/keystore-regression-versions/cc-keystore-09/Cargo.toml, extras/keystore-regression-versions/cc-keystore-10p/Cargo.toml, extras/keystore-regression-versions/cc-keystore-10r/Cargo.toml, extras/keystore-regression-versions/cc-keystore-current/Cargo.toml, extras/keystore-regression-versions/cc-keystore-support/Cargo.toml, extras/wasm-browser-run/Cargo.toml, extras/wasm-browser-test-runner/Cargo.toml, keystore-dump/Cargo.toml, keystore/Cargo.toml, package.json
=> misc: Fix licenses & clarify advisories

crypto-ffi/src/generic.rs, crypto-ffi/src/wasm.rs, crypto/Cargo.toml, crypto/src/e2e_identity/init_certificates.rs, crypto/src/e2e_identity/mod.rs, crypto/src/e2e_identity/rotate.rs, crypto/src/mls/conversation/commit.rs, crypto/src/mls/conversation/decrypt.rs, crypto/src/mls/conversation/proposal.rs, crypto/src/mls/conversation/self_commit.rs, crypto/src/mls/conversation/welcome.rs, crypto/src/mls/credential/crl.rs, crypto/src/mls/external_commit.rs, crypto/src/test_utils/x509.rs
=> fix: deduplicate CRL DPs

crypto-ffi/src/wasm.rs, crypto/src/mls/conversation/welcome.rs, crypto/src/test_utils/x509.rs
=> fix: catch the "NoMatchingEncryptionKey" error from openmls and also return a "OrphanWelcome" one

crypto/src/e2e_identity/conversation_state.rs
=> feat!: introduce `e2ei_verify_group_state` to preemptively check a group state through its GroupInfo before joining it

crypto-ffi/bindings/js/CoreCrypto.ts, crypto-ffi/bindings/js/test/CoreCrypto.test.js, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/MlsModel.kt, crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift, crypto-ffi/src/generic.rs, crypto-ffi/src/wasm.rs, crypto/src/e2e_identity/device_status.rs, crypto/src/e2e_identity/identity.rs, crypto/src/e2e_identity/rotate.rs, crypto/src/error.rs, crypto/src/lib.rs, crypto/src/mls/conversation/decrypt.rs, crypto/src/mls/conversation/mod.rs, crypto/src/mls/conversation/self_commit.rs, crypto/src/mls/credential/ext.rs, crypto/src/mls/credential/typ.rs, crypto/src/test_utils/central.rs
=> feat!: WireIdentity works for Basic members [WPB-5975]

crypto-ffi/src/generic.rs, crypto-ffi/src/wasm.rs, crypto/src/e2e_identity/mod.rs, crypto/src/e2e_identity/rotate.rs, crypto/src/e2e_identity/stash.rs
----
----
Double free issues on Swift
----
=> feat!: borrow enrollment instead of requiring ownership

crypto/src/e2e_identity/crypto.rs, crypto/src/e2e_identity/error.rs, crypto/src/e2e_identity/mod.rs, crypto/src/test_utils/fixtures.rs, mls-provider/src/pki.rs
----
----
Seeding an P-curve signature key to e2ei was not working
----
=> fix: e2ei with NIST P-curves

crypto-ffi/src/generic.rs, crypto-ffi/src/wasm.rs, crypto/Cargo.toml, crypto/src/mls/conversation/config.rs, mls-provider/src/crypto_provider.rs
=> feat: support JWK external sender [WPB-1193]

.github/workflows/bindings.yml, CHANGELOG.tpl, Cargo.toml, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/CoreCryptoCentral.kt, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/MlsModel.kt, crypto-ffi/bindings/swift/build-xcframework.sh, crypto-ffi/src/generic.rs, crypto-ffi/src/wasm.rs, crypto-ffi/uniffi.toml, crypto/src/e2e_identity/conversation_state.rs, crypto/src/mls/conversation/decrypt.rs, crypto/src/mls/external_commit.rs, crypto/src/mls/mod.rs, crypto/src/test_utils/mod.rs
=> chore!: UniFFI 0.27 upgrade

crypto-ffi/src/wasm.rs, crypto/src/mls/credential/ext.rs, interop/src/clients/mod.rs
=> fix: Ciphersuite being ignored on WASM createConversation

crypto-attributes/README.md, crypto-ffi/README.md, crypto/README.md, keystore-dump/README.md, mls-provider/README.md
=> doc: document crates [wpb-9171]

crypto-ffi/Cargo.toml, crypto-ffi/bindings/js/CoreCrypto.ts, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/CoreCryptoCentral.kt, crypto-ffi/src/generic.rs, crypto-ffi/src/wasm.rs, crypto/src/lib.rs
----
----
Expose the logging API publicity. https://github.com/wireapp/core-crypto/pull/552 Needs to be merged first.
----
=> feat: Expose logging to public API [WPB-7260]

crypto/src/mls/credential/mod.rs
=> test: crypto: box the future so we don't blow up the stack

.github/workflows/audit.yml, .github/workflows/bindings.yml, .github/workflows/coverage.yml, .github/workflows/deny.yml, .github/workflows/docs.yml, .github/workflows/publish-android.yml, .github/workflows/publish-jvm.yml, .github/workflows/publish-swift.yml, .github/workflows/publish-wasm.yml, .github/workflows/rust.yml
=> chore: remove sccache action, fix yaml syntax error

.github/workflows/rust.yml
This PR moves certain tasks around and eliminates some obvious duplication of tasks, which should help with overall CI times.
----
=> ci: improve CI

README.md
Fixes the outdated commands to build the bindings.
----
----
The build instruction in the README file are not up-to-date
Update the README
----
=> doc: fix bindings instructions in README.md

package.json
=> chore: package.json: use the team's e-mail address

crypto-ffi/bindings/js/CoreCrypto.ts, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/CoreCryptoCentral.kt, crypto-ffi/src/generic.rs, crypto-ffi/src/wasm.rs
This adds the log level to the log callback
----
=> feat: add log level to the callback [WPB-7260]

.cargo/config.toml
=> chore: remove unnecessary things from cargo config

Cargo.toml, crypto-ffi/Cargo.toml, crypto-ffi/Makefile.toml, crypto/Cargo.toml, interop/Cargo.toml, keystore/Cargo.toml, mls-provider/Cargo.toml
Update dependencies to latest versions, remove the pin on the openssl-sys crate to a fixed version and fix task to build android on mac os
----
=> chore: Update dependencies and fix android build on Mac [WPB-9740]

crypto/src/mls/conversation/own_commit.rs
=> style: fix typo

crypto/src/lib.rs
=> chore: crypto: remove unnecessary use

keystore/src/entities/mod.rs
=> chore: remove unused function [WPB-10106]

crypto/src/mls/conversation/export.rs, keystore/build.rs, xtask/Cargo.lock, xtask/Cargo.toml, xtask/src/release/bump.rs, xtask/src/release/mod.rs
=> chore: update dependencies in release script and fix clippy warnings

crypto/src/e2e_identity/mod.rs, crypto/src/e2e_identity/rotate.rs, crypto/src/e2e_identity/stash.rs, crypto/src/mls/client/key_package.rs
=> fix: get_or_create_key_packages() must respect credential type [WPB-10294]

xtask/src/release/bump.rs
To be compatible with dependencies specified as normal table (not just inline)
----
=> build: Fix version bump script

xtask/src/release/bump.rs
To be in line with what was done in #610.
See commit message
----
=> build: Adjust version bump script

CHANGELOG.md, CHANGELOG.tpl, Cargo.lock, Cargo.toml, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto-ffi/bindings/gradle.properties, crypto/Cargo.toml, interop/Cargo.toml, keystore-dump/Cargo.toml, keystore/Cargo.toml, mls-provider/Cargo.toml, package.json
=> build: release v1.0.1

crypto/src/e2e_identity/identity.rs, crypto/src/test_utils/mod.rs, crypto/src/test_utils/x509.rs
This adds 2 new tests for cross signing certificates. 
----
=> tests: add cross signing tests [WPB-7264]

crypto-ffi/Makefile.toml
Make use of reproducible builds when building.
----
=> build: add --locked flag to build commands

.github/workflows/rust.yml
CI needs to generate junit report on tags
----
=> fix: run ci to generate junit report on tags [WPB-10608]

keystore/Cargo.toml, keystore/src/connection/platform/generic/migrations/V12__unique_id_constraints.sql, keystore/src/connection/platform/generic/mod.rs, keystore/src/entities/mod.rs, keystore/src/entities/platform/generic/mls/e2ei_crl.rs, keystore/src/entities/platform/generic/mls/e2ei_intermediate_cert.rs, keystore/src/entities/platform/generic/mls/encryption_keypair.rs, keystore/src/entities/platform/generic/mls/enrollment.rs, keystore/src/entities/platform/generic/mls/epoch_encryption_keypair.rs, keystore/src/entities/platform/generic/mls/group.rs, keystore/src/entities/platform/generic/mls/hpke_private_key.rs, keystore/src/entities/platform/generic/mls/keypackage.rs, keystore/src/entities/platform/generic/mls/psk_bundle.rs, keystore/src/entities/platform/generic/proteus/prekey.rs, keystore/src/entities/platform/generic/proteus/session.rs, keystore/src/lib.rs, keystore/src/mls.rs, keystore/tests/z_entities.rs
Optimizing `save()` method on may entities.
----
=> refactor: improve keystore [WPB-3374]

.github/workflows/coverage.yml
Let's see if problems pop up with this gone.
=> chore: ci: remove seemingly needless "disk space maintenance" step

Cargo.lock, crypto/src/mls/proposal.rs
=> chore: update dependency lock

.github/workflows/bindings.yml, crypto-ffi/bindings/jvm/src/test/kotlin/com/wire/crypto/client/E2EITest.kt, crypto-ffi/bindings/jvm/src/test/kotlin/com/wire/crypto/client/MLSTest.kt
=> chore: fix kotlin tests

CHANGELOG.md, Cargo.lock, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto-ffi/bindings/gradle.properties, crypto/Cargo.toml, interop/Cargo.toml, keystore-dump/Cargo.toml, keystore/Cargo.toml, mls-provider/Cargo.toml, package.json
=> build: release 1.1.0

.pre-commit-config.yaml, README.md
This framework enables arbitrary pre-commit hooks to streamline our development workflow and reduce pull request review time. Use of these hooks is opt-in and optional.
----
=> build: add pre-commit configuration and documentation [WPB-14263]

CHANGELOG.md, Cargo.lock, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto-ffi/bindings/gradle.properties, crypto/Cargo.toml, interop/Cargo.toml, keystore-dump/Cargo.toml, keystore/Cargo.toml, mls-provider/Cargo.toml, package.json
- Improve errors when hitting an indexdb error during cryptobox migration (3266550)
----
=> build: release 1.1.1

CHANGELOG.md, Cargo.lock, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto-ffi/bindings/gradle.properties, crypto/Cargo.toml, interop/Cargo.toml, keystore-dump/Cargo.toml, keystore/Cargo.toml, mls-provider/Cargo.toml, package.json
=> build: release 1.1.2

crypto-ffi/Makefile.toml, crypto-ffi/src/wasm/context/e2ei.rs, crypto/src/e2e_identity/conversation_state.rs, crypto/src/lib.rs, crypto/src/mls/credential/mod.rs, crypto/src/test_utils/x509.rs, keystore/src/connection/platform/generic/mod.rs
After upgrading to Rust 1.83, new Clippy warnings appeared.
----
=> chore: apply suggested clippy fixes

.github/actions/run-bencher/action.yml, .github/workflows/benchmarks.yml, .github/workflows/bindings.yml, README.md, crypto-ffi/bindings/js/benches/CoreCrypto.bench.ts, crypto-ffi/bindings/js/test/CoreCrypto.test.ts, crypto-ffi/bindings/js/test/utils.ts, crypto-ffi/bindings/js/wdio.conf.ts, crypto/Cargo.toml, crypto/benches/transaction.rs, crypto/benches/utils/mls.rs, crypto/benches/utils/mod.rs, crypto/benches/utils/proteus_bench.rs, package.json
Adds benches and runs them in CI. The benches were used for an investigation regarding transactions and group store.
----
=> chore: add transaction bench and web bench

.github/workflows/bindings.yml
This will reduce the CI runtime.
----
=> ci: build swift targets in parallel

crypto/src/mls/conversation/durability.rs
=> chore: remove leftover tracing attribute

crypto-ffi/bindings/js/CoreCrypto.ts, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/CoreCrypto.kt, crypto-ffi/src/generic/mod.rs, crypto-ffi/src/wasm/mod.rs, crypto/src/context.rs, crypto/src/error.rs, crypto/src/lib.rs, crypto/src/mls/conversation/buffer_messages.rs, crypto/src/mls/conversation/commit.rs, crypto/src/mls/conversation/decrypt.rs, crypto/src/mls/external_commit.rs, crypto/src/mls/external_proposal.rs, crypto/src/mls/mod.rs, crypto/src/test_utils/mod.rs
=> feat!: add transport api [WPB-12119] remove validation callbacks [WPB-14463]

.github/workflows/bindings.yml, crypto-ffi/bindings/android/build.gradle.kts
In addition to building the wrapper also run the tests on an android emulator.
----
=> feat: instrumented android tests [WPB-12175]

CHANGELOG.md, Cargo.lock, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto-ffi/bindings/gradle.properties, crypto/Cargo.toml, interop/Cargo.toml, keystore-dump/Cargo.toml, keystore/Cargo.toml, mls-provider/Cargo.toml, package.json
=> build: release 3.0.0

CHANGELOG.md
Cherry pick change log update from release/3.x
----
=> chore: update changelog for 3.0.0

crypto-ffi/bindings/js/test/CoreCrypto.test.ts, crypto-ffi/bindings/js/test/utils.ts, crypto-ffi/bindings/jvm/src/test/kotlin/com/wire/crypto/MLSTest.kt, crypto-ffi/src/generic/mod.rs, crypto/src/e2e_identity/error.rs, crypto/src/error/proteus.rs, crypto/src/error/recursive.rs, crypto/src/mls/client/error.rs, crypto/src/mls/conversation/error.rs, crypto/src/mls/credential/mod.rs, crypto/src/mls/error.rs, crypto/src/test_utils/error.rs
=> fix: manually implement std::error::Error for RecursiveError, fix `LeafError` mapping

.github/workflows/bindings.yml, crypto-ffi/Makefile.toml, crypto-ffi/bindings/js/benches/CoreCrypto.bench.ts, crypto-ffi/bindings/js/wdio.conf.ts
Fix some type errors and thereby make TS docs generation work again. Also ensure we catch such errors earlier in the future.
=> chore: fix TS docs generation

crypto-ffi/bindings/js/src/CoreCrypto.ts, crypto-ffi/bindings/js/src/CoreCryptoContext.ts, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/CoreCryptoContext.kt, crypto-ffi/bindings/jvm/src/test/kotlin/com/wire/crypto/MLSTest.kt, crypto-ffi/src/generic/context/mod.rs, crypto-ffi/src/generic/mod.rs, crypto-ffi/src/wasm/context/mod.rs, crypto/src/e2e_identity/rotate.rs, crypto/src/mls/conversation/commit.rs, crypto/src/mls/conversation/error.rs, crypto/src/mls/external_commit.rs, crypto/src/test_utils/mod.rs
=> fix!: fix mls transport retry case, remove proposal api [WBP-15290]

crypto-ffi/bindings/js/src/CoreCrypto.ts, crypto-ffi/bindings/js/src/CoreCryptoInstance.ts, crypto-ffi/bindings/js/test/utils.ts, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/CoreCrypto.kt, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/E2EIEnrollment.kt, crypto-ffi/bindings/jvm/src/test/kotlin/com/wire/crypto/ProteusClientTest.kt, crypto-ffi/src/generic/context/mod.rs, crypto-ffi/src/generic/mod.rs, crypto/src/mls/external_commit.rs, crypto/src/proteus.rs, interop/src/clients/InteropClient/InteropClient/InteropClientApp.swift, interop/src/clients/corecrypto/web.rs
=> refactor!: remove deprecated transaction functions [WPB-15292]

CHANGELOG.md, Cargo.lock, crypto-attributes/Cargo.toml, crypto-ffi/Cargo.toml, crypto-ffi/bindings/gradle.properties, crypto/Cargo.toml, interop/Cargo.toml, keystore-dump/Cargo.toml, keystore/Cargo.toml, mls-provider/Cargo.toml, package.json
=> build: release 3.0.1

CHANGELOG.md
Update changelog to contain info about the latest release
----
=> chore: update changelog for 3.0.1

.github/workflows/publish-jvm.yml
=> chore: ci: use correct task name

CHANGELOG.md
=> chore: update changelog for 3.0.2

CHANGELOG.md, Cargo.lock, crypto-ffi/Cargo.toml, crypto-ffi/bindings/gradle.properties, crypto-ffi/bindings/js/package.json, crypto-macros/Cargo.toml, crypto/Cargo.toml, interop/Cargo.toml, keystore-dump/Cargo.toml, keystore/Cargo.toml, mls-provider/Cargo.toml
=> Prepare release/4.1.0

CHANGELOG.md, Cargo.lock, crypto-ffi/Cargo.toml, crypto-ffi/bindings/gradle.properties, crypto-macros/Cargo.toml, crypto/Cargo.toml, interop/Cargo.toml, keystore-dump/Cargo.toml, keystore/Cargo.toml, mls-provider/Cargo.toml, package.json, scripts/update-versions.sh
=> Prepare-release: 3.1.0

crypto-ffi/Makefile.toml
Replace usage of dokka CLI tool with the dokka gradle plugin which is already configured for all kotlin projects.
----
=> refactor: re-work how we generate kotlin docs [WPB-16036]

CHANGELOG.md, Cargo.lock, crypto-ffi/Cargo.toml, crypto-ffi/bindings/gradle.properties, crypto-ffi/bindings/js/package.json, crypto-macros/Cargo.toml, crypto/Cargo.toml, interop/Cargo.toml, keystore-dump/Cargo.toml, keystore/Cargo.toml, mls-provider/Cargo.toml
=> chore: prepare 4.2.0 release 

.github/workflows/bindings.yml, .github/workflows/rust.yml, Cargo.lock, crypto-ffi/Cargo.toml, crypto-ffi/bindings/swift/WireCoreCrypto/WireCoreCrypto.xcodeproj/project.pbxproj, crypto-ffi/bindings/swift/WireCoreCrypto/WireCoreCrypto/WireCoreCrypto.h, crypto/Cargo.toml, crypto/src/lib.rs, deny.toml
core-crypto does/should not need uniffi.
=> chore: remove uniffi from crypto

.github/workflows/docs.yml
=> ci: fix docs landing page copying

.github/workflows/docs.yml
This is required for the feature to convert the index.md file to html.
See above
----
=> ci: enable jekyll for github pages

README.md, docs/index.md
=> docs: update table in index.md 

crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/CoreCryptoContext.kt
=> fix(kt-wrapper): expose `proteusCryptoboxMigrate()` [WPB-16549]

CHANGELOG.md, Cargo.lock, crypto-ffi/Cargo.toml, crypto-ffi/bindings/gradle.properties, crypto-ffi/bindings/js/package.json, crypto-macros/Cargo.toml, crypto/Cargo.toml, docs/index.md, interop/Cargo.toml, keystore-dump/Cargo.toml, keystore/Cargo.toml, mls-provider/Cargo.toml
=> build: release 4.2.1

CHANGELOG.md, Cargo.lock, crypto-ffi/Cargo.toml, crypto-ffi/bindings/gradle.properties, crypto-ffi/bindings/js/package.json, crypto-macros/Cargo.toml, crypto/Cargo.toml, docs/index.md, interop/Cargo.toml, keystore-dump/Cargo.toml, keystore/Cargo.toml, mls-provider/Cargo.toml
=> build: release 4.2.2

crypto-ffi/bindings/android/build.gradle.kts
=> fix: the android artefact was still trying to publish to nexus

crypto-ffi/bindings/swift/WireCoreCrypto/WireCoreCrypto/CoreCrypto.swift, crypto-ffi/bindings/swift/WireCoreCrypto/WireCoreCryptoTests/WireCoreCryptoTests.swift
Add API for observing epochs to the swift bindings
----
=> feat: add API for observing epochs to the swift bindings [WPB-16561]

.github/workflows/bindings.yml
run swift lint on the Swift wrapper
----
=> chore: run swift lint on the Swift wrapper [WPB-15511]

keystore/src/connection/platform/generic/ios_wal_compat.rs, keystore/src/connection/platform/generic/mod.rs
This PR simplifies the situation around `handle_ios_wal_compat`.
=> chore: simplify handle_ios_wal_compat

crypto/src/mls/client/identities.rs, crypto/src/mls/conversation/commit.rs, crypto/src/mls/conversation/mod.rs, crypto/src/mls/conversation/proposal.rs, crypto/src/mls/external_proposal.rs, crypto/src/test_utils/context.rs
=> refactor: centralize `MlsConversation` impl blocks [WPB-15529]

.github/actions/setup-and-cache-rust/action.yml, .github/workflows/bindings.yml, .github/workflows/build-ios.yml
=> ci: fix macos runner rust setup and cache

.github/dependabot.yml
Also consider Cargo manifests in all directories.
=> chore: add bun to dependabot config

.github/workflows/publish-swift.yml, crypto-ffi/bindings/swift/BuildSettings.xcconfig, crypto-ffi/bindings/swift/WireCoreCrypto/WireCoreCrypto.xcodeproj/project.pbxproj, crypto-ffi/bindings/swift/WireCoreCrypto/WireCoreCrypto/CoreCrypto.swift, crypto-ffi/bindings/swift/WireCoreCrypto/WireCoreCrypto/WireCoreCrypto.h, crypto-ffi/bindings/swift/WireCoreCryptoUniffi/WireCoreCryptoUniffi.xcodeproj/project.pbxproj, crypto-ffi/bindings/swift/build-xcframework.sh, interop/src/clients/InteropClient/InteropClient.xcodeproj/project.pbxproj
=> fix: broken swift bindings by publishing uniffi framework separately

crypto-ffi/Makefile.toml, crypto-ffi/bindings/js/src/CoreCrypto.ts, crypto-ffi/bindings/js/src/CoreCryptoInstance.ts
=> chore: fix doc warnings in js bindings and prevent new ones [WPB-15450]

crypto-ffi/bindings/js/src/CoreCryptoContext.ts
=> chore: fix tsdoc warning

crypto/src/group_store.rs, crypto/src/lib.rs, crypto/src/proteus.rs
=> refactor(proteus): centralize `ProteusConversationSession` [WPB-15528]

crypto-ffi/bindings/swift/WireCoreCrypto/WireCoreCrypto/CoreCrypto.swift, crypto-ffi/bindings/swift/WireCoreCrypto/WireCoreCryptoTests/WireCoreCryptoTests.swift
For consistency in the bindings we should also re-throw inner error which cancelled the transaction in the Swift wrapper.
----
=> fix: re-throw inner error which cancelled the transaction

README.md
This updates the readme with info about making releases from a release branch
See above
----
=> docs: update `Readme.md`

crypto-ffi/bindings/jvm/src/test/kotlin/com/wire/crypto/MLSTest.kt
This extends the scenario to also include an epoch change by another member
----
=> test: Kotlin: extend epoch observer test

rust-toolchain.toml
=> chore: add rust-analyzer to rust-toolchain.toml

Cargo.lock, Cargo.toml
We also have to update uuid as a result.
=> chore: update to rusty-jwt-tools 0.13.0

.github/workflows/bindings.yml, crypto-ffi/bindings/gradle/libs.versions.toml, crypto-ffi/bindings/jvm/build.gradle.kts, crypto-ffi/bindings/jvm/detekt.yml, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/ByteUtils.kt, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/CoreCrypto.kt, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/CoreCryptoContext.kt, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/CoreCryptoException.kt, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/E2EIEnrollment.kt, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/MlsModel.kt, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/ProteusModel.kt, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/Uniffi.kt
This PR makes use of detekt to check for documentation inconsistencies and enables the check on CI.
=> chore: use detekt to check docs (WPB-15467)

crypto/src/mls/conversation/commit.rs, crypto/src/mls/conversation/conversation_guard/commit.rs, crypto/src/mls/conversation/conversation_guard/decrypt/buffer_messages.rs, crypto/src/mls/conversation/conversation_guard/merge.rs, crypto/src/test_utils/context.rs
=> fix: clear pending commit before creating a new one [WPB-17356]

Cargo.toml, crypto/src/mls/conversation/mod.rs, crypto/src/mls/conversation/pending_conversation.rs, crypto/src/test_utils/context.rs, crypto/src/test_utils/mod.rs, crypto/src/test_utils/test_context.rs, crypto/src/test_utils/test_conversation.rs
=> feat(test): add `TestConversation` test abstraction [WPB-15784]

CHANGELOG.md, docs/index.md
(cherry picked from commit 09906735c1522d5947dc0ed11cc78960d78b4d81)
----
=> build: update docs and changelog for 5.4.0

crypto-ffi/src/bundles/welcome.rs
Fix WelcomeBundle field names and attributes on Wasm.
=> fix: js bindings welcome bundle naming and attributes

crypto-ffi/bindings/js/src/CoreCrypto.ts, crypto-ffi/bindings/js/test/bun/utils.ts, crypto-ffi/bindings/js/test/wdio/utils.ts, interop/src/clients/corecrypto/web.rs
=> feat: remove top level await and expose async init method instead [WPB-17698]

crypto/src/mls/conversation/own_commit.rs, crypto/src/test_utils/context.rs
Add test case for incoming lost self-commit. 
Spent a bunch of work trying to also make the case pass the way we want it to, but couldn't work it out. OpenMLS just doesn't expose the right primitives to allow for this operation.
----
=> test: add test case for incoming lost self-commit [WPB-17464]

crypto/src/mls/conversation/commit_delay.rs
Just for better readability
See above
----
=> refactor(conversation): invert if in `compute_commit_delay()`

crypto-ffi/bindings/js/src/CoreCrypto.ts, crypto-ffi/bindings/js/src/CoreCryptoInstance.ts, crypto-ffi/bindings/js/src/CoreCryptoMLS.ts, crypto-ffi/bindings/js/test/bun/utils.ts, crypto-ffi/bindings/js/test/wdio/utils.ts, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/CoreCrypto.kt, crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/MlsModel.kt, crypto-ffi/bindings/jvm/src/test/kotlin/com/wire/crypto/MLSTest.kt, crypto-ffi/bindings/swift/WireCoreCrypto/WireCoreCrypto/CoreCrypto.swift, crypto-ffi/bindings/swift/WireCoreCrypto/WireCoreCryptoTests/WireCoreCryptoTests.swift, crypto-ffi/src/core_crypto/history_observer.rs, crypto-ffi/src/core_crypto/mls_transport.rs, crypto-ffi/src/core_crypto/mod.rs, crypto-ffi/src/ephemeral.rs, crypto-ffi/src/lib.rs, crypto/benches/utils/mls.rs, crypto/src/ephemeral.rs, crypto/src/lib.rs, crypto/src/mls/mod.rs, crypto/src/mls/session/error.rs, crypto/src/mls/session/history_observer.rs, crypto/src/mls/session/mod.rs, crypto/src/test_utils/history_observer.rs, crypto/src/test_utils/mod.rs, interop/src/clients/InteropClient/InteropClient/InteropClientApp.swift, interop/src/util.rs
=> feat: history observer

README.md
=> docs/fix invalid API Docs link in README.md

crypto-ffi/src/metadata.rs, crypto-macros/src/entity_derive/derive_impl.rs, crypto/src/error/recursive.rs, crypto/src/mls/conversation/commit_delay.rs, crypto/src/mls/mod.rs, crypto/src/test_utils/mod.rs, crypto/src/test_utils/x509.rs, interop/src/main.rs, keystore/src/connection/platform/generic/mod.rs, mls-provider/src/pki.rs, rust-toolchain.toml
=> chore: upgrade rust to 1.88

.github/workflows/docs.yml, crypto-ffi/Makefile.toml, crypto-ffi/bindings/swift/WireCoreCrypto/WireCoreCrypto/WireCoreCrypto.docc/WireCoreCrypto.md, crypto-ffi/src/core_crypto/command/mod.rs, crypto-ffi/src/core_crypto/mod.rs
=> doc(swift): build swift documentation in CI

.github/workflows/docs.yml
=> doc(swift): upload swift docs into the right folder

CHANGELOG.md, crypto-ffi/bindings/js/src/CoreCryptoInstance.ts, crypto-ffi/src/core_crypto/mod.rs, crypto/src/mls/session/mod.rs, keystore/src/connection/mod.rs, mls-provider/src/lib.rs
=> feat!: remove `can_close()` [WPB-17633]

docs/index.md
=> docs: remove unintended code comment showing up in  `index.md`

keystore/src/transaction/mod.rs
During the review of 18ccd2dd958cba735ac35e3d12ad92925be5d941, we learned that we can have dynamically typed iterators without heap allocation easily. We can use this knowledge to get some performance gain here.
----
=> refactor(transaction): avoid unnecessary `collect()` when merging records

crypto-ffi/Makefile.toml, crypto-ffi/bindings/android/build.gradle.kts, crypto-ffi/bindings/jvm/build.gradle.kts
=> chore: simplify gradle setup by avoiding the need to copy source files

crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/MlsModel.kt
=> chore(jvm): add `MLSKeyPackage.copyBytes()`

.editorconfig, .github/workflows/toml.yml, Cargo.toml, cliff.toml, crypto-ffi/Cargo.toml, crypto/Cargo.toml, deny.toml, interop/Cargo.toml, keystore-dump/Cargo.toml, keystore/Cargo.toml
=> build: check formatting of all toml files in the repo [WPB-15481]

.github/workflows/toml.yml
=> chore: update `setup-fd` target

.github/workflows/bindings.yml, scripts/debug-xcode.sh
=> ci: fix swift docs [WPB-19555]

.github/workflows/bindings.yml
=> ci: `chmod +x target/release/uniffi-bindgen` as necessary

.github/workflows/bindings.yml, Makefile
Error if there are no files before uploading docs.
Fix swift docs directory in makefile.
----
=> docs: fix swift docs directory in makefile

.github/workflows/build-jvm-linux.yml, Makefile
=> build: add heuristics when building jvm [WPB-19443]

crypto-ffi/bindings/js/README.md
=> docs: add js README for npm [WPB-17231]

README.md
=> chore: document make min version

Makefile, crypto-ffi/bindings/android/build.gradle.kts, crypto-ffi/bindings/jvm/build.gradle.kts
This makes gradle debug builds work properly.
=> build: allow debug android builds

.github/actions/make/action.yml, .github/actions/make/android/lib/action.yml, .github/actions/make/android/package/action.yml, .github/actions/make/bindings-kotlin-jvm/action.yml, .github/actions/make/bindings-swift/action.yml, .github/actions/make/ffi-library/action.yml, .github/actions/make/ios/action.yml, .github/actions/make/jvm-linux/action.yml, .github/actions/make/uniffi-bindgen/action.yml, .github/workflows/bindings.yml, Makefile
=> ci: use hash of prerequisite files for artifact keys [WPB-17419]

CHANGELOG.md, Cargo.lock, decode/Cargo.toml, decode/src/main.rs
=> feat(decode): add options for listing members or identities

.github/workflows/publish-android.yml, .github/workflows/publish-jvm.yml, .github/workflows/publish-swift.yml, .github/workflows/publish-wasm.yml, .github/workflows/rust.yml, CHANGELOG.md, Makefile
=> fix: include previously (v8.x) missing artifacts in released web package

.github/workflows/pipeline.yml, .github/workflows/publish-android.yml, .github/workflows/publish-jvm.yml
=> ci: fix: provide missing `SONATYPE_USERNAME`
